#!/usr/bin/env python3
"""Build metadata and verify the exact bytes distributed by each SDK release."""
from __future__ import annotations

import argparse
import email
import hashlib
import json
import os
import plistlib
import re
import shutil
import subprocess
import tarfile
import tomllib
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
METADATA = "release-metadata.json"
SWIFT_METADATA = "swift/release-artifacts.json"
SWIFT_SOURCE = "swift/Sources/WasmerSDKCore/WasmerSDKCore.swift"
GENERATED = {"Package.swift", SWIFT_METADATA, SWIFT_SOURCE}
PLATFORMS = {"linux-x86_64", "linux-arm64", "macos-x86_64", "macos-arm64"}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def read_json(path: Path) -> dict:
    return json.loads(path.read_text())


def digest(path: Path) -> str:
    result = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            result.update(block)
    return result.hexdigest()


def version(component: str, root: Path = ROOT, tag: str | None = None) -> str:
    if component == "swift":
        value = (root / "swift/version.txt").read_text().strip()
    elif component == "js":
        package = read_json(root / "js/package.json")
        lock = read_json(root / "js/package-lock.json")
        require(package["name"] == "@wasmer/sdk", "Unexpected npm package identity")
        value = package["version"]
        require(lock["version"] == value and lock["packages"][""]["version"] == value,
                "npm package and lockfile versions differ")
    else:
        package = tomllib.loads((root / "python/pyproject.toml").read_text())["project"]
        require(package["name"] == "wasmer-sdk", "Unexpected Python package identity")
        value = package["version"]
    require(bool(re.fullmatch(r"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)", value)),
            "Release automation currently requires a stable MAJOR.MINOR.PATCH version")
    if tag is not None:
        require(tag == release_tag(component, value), f"{tag} differs from {component} version {value}")
    return value


def source_digest(root: Path = ROOT) -> str:
    """Bind Swift's pre-tag build to its inputs, independent of merge commit SHA."""
    names = subprocess.check_output(["git", "ls-files", "-z"], cwd=root).decode().split("\0")
    result = hashlib.sha256()
    # Ignore unrelated JS/Python/docs changes so independent releases can merge.
    inputs = {name for name in names if name.startswith(("rust/", "swift/", ".cargo/", ".github/"))
              or name in {"Cargo.toml", "Cargo.lock", "rust-toolchain.toml"}}
    for name in sorted(inputs - GENERATED):
        path = root / name
        require(path.is_file() or path.is_symlink(), f"Missing tracked release input: {name}")
        value = (hashlib.sha256(os.readlink(path).encode()).hexdigest()
                 if path.is_symlink() else digest(path))
        mode = "link" if path.is_symlink() else str(path.stat().st_mode & 0o111)
        result.update(f"{name}\0{mode}\0{value}\0".encode())
    return result.hexdigest()


def swift_archive(value: str) -> str:
    return f"WasmerSDKFFI-{value}-macos-universal.zip"


def release_tag(component: str, value: str) -> str:
    return f"wasmer-sdk-{component}-v{value}"


def swift_manifest(value: str, repository: str, checksum: str | None) -> str:
    binary = ('path: "swift/Artifacts/WasmerSDKFFI.xcframework"' if checksum is None else
              f'url: "https://github.com/{repository}/releases/download/{release_tag("swift", value)}/{swift_archive(value)}",\n'
              f'      checksum: "{checksum}"')
    return f'''// swift-tools-version: 6.0
// Generated by .github/scripts/sdk_release.py. The release PR pins the binary checksum.
import PackageDescription

let package = Package(
  name: "WasmerSDK",
  platforms: [.macOS(.v12), .iOS("27.0")],
  products: [
    .library(name: "WasmerSDK", targets: ["WasmerSDK"]),
    .library(name: "WasmerWKSDK", type: .static, targets: ["WasmerWKSDK"]),
  ],
  targets: [
    .binaryTarget(name: "WasmerSDKFFI", {binary}),
    .target(
      name: "WasmerSDKCore", dependencies: ["WasmerSDKFFI"],
      path: "swift/Sources/WasmerSDKCore",
      linkerSettings: [
        .linkedLibrary("c++"), .linkedLibrary("iconv"), .linkedLibrary("resolv"),
        .linkedFramework("Security"), .linkedFramework("SystemConfiguration"),
        .linkedFramework("CoreFoundation"),
      ]
    ),
    .target(name: "WasmerSDK", dependencies: ["WasmerSDKCore"], path: "swift/Sources/WasmerSDK"),
    .target(
      name: "WasmerWKSDK", path: "swift/WasmerWKSDK/Sources/WasmerWKSDK",
      resources: [.copy("Web")]
    ),
  ]
)
'''


def wheel_platform(filename: str) -> str:
    platform = filename.removesuffix(".whl").rsplit("-", 1)[-1]
    if "manylinux" in platform:
        if platform.endswith("_x86_64"):
            return "linux-x86_64"
        if platform.endswith("_aarch64"):
            return "linux-arm64"
    if platform.startswith("macosx_"):
        if platform.endswith("_x86_64"):
            return "macos-x86_64"
        if platform.endswith("_arm64"):
            return "macos-arm64"
    raise ValueError(f"Unexpected or unrepaired wheel platform: {filename}")


def validate_assets(directory: Path, component: str, value: str) -> dict[str, str]:
    """Check embedded package identities and the complete platform matrix."""
    npm = list(directory.glob("*.tgz"))
    wheels = list(directory.glob("*.whl"))
    archives = list(directory.glob("*.zip"))
    expected = {"js": (1, 0, 0), "python": (0, 4, 0), "swift": (0, 0, 1)}[component]
    require((len(npm), len(wheels), len(archives)) == expected,
            f"Wrong artifact set for {component}: expected {expected} (npm, wheels, Swift)")
    for tarball in npm:
        with tarfile.open(tarball) as archive:
            stream = archive.extractfile("package/package.json")
            require(stream is not None, "npm tarball has no package.json")
            package = json.load(stream)
            require(package["name"] == "@wasmer/sdk" and package["version"] == value,
                    "npm tarball identity/version differs from release")
            names = archive.getnames()
            require("package/dist/node.js" in names and "package/dist/index.js" in names
                    and any(name.endswith(".wasm") for name in names),
                    "npm tarball must include Node, browser, and Wasm artifacts")
    platforms = []
    for wheel in wheels:
        require(wheel.name.startswith(f"wasmer_sdk-{value}-py3-none-"),
                f"Unexpected Python wheel name: {wheel.name}")
        platforms.append(wheel_platform(wheel.name))
        with zipfile.ZipFile(wheel) as archive:
            metadata = [name for name in archive.namelist() if name.endswith(".dist-info/METADATA")]
            require(len(metadata) == 1, f"Invalid wheel metadata: {wheel.name}")
            package = email.message_from_bytes(archive.read(metadata[0]))
            require(package["Name"] == "wasmer-sdk" and package["Version"] == value,
                    f"Wheel metadata differs from release: {wheel.name}")
            require(any(name.startswith("wasmer_sdk/") and name.endswith((".so", ".dylib"))
                        for name in archive.namelist()), f"Missing native library: {wheel.name}")
    if wheels:
        require(set(platforms) == PLATFORMS, "Missing or duplicate Python wheel platform")
    for bundle in archives:
        require(bundle.name == swift_archive(value), "Unexpected Swift archive name")
        with zipfile.ZipFile(bundle) as archive:
            prefix = "WasmerSDKFFI.xcframework/"
            info = plistlib.loads(archive.read(prefix + "Info.plist"))
            libraries = info["AvailableLibraries"]
            require(len(libraries) == 1 and libraries[0]["SupportedPlatform"] == "macos"
                    and set(libraries[0]["SupportedArchitectures"]) == {"arm64", "x86_64"},
                    "Swift release must be a universal macOS XCFramework")
            library = libraries[0]
            base = prefix + library["LibraryIdentifier"] + "/"
            for member in (base + library["LibraryPath"], base + library["HeadersPath"] + "/module.modulemap"):
                require(member in archive.namelist(), f"Incomplete XCFramework: {member}")
    return {path.name: digest(path) for path in sorted([*npm, *wheels, *archives])}


def checksums(files: dict[str, str]) -> str:
    return "".join(f"{checksum}  {name}\n" for name, checksum in sorted(files.items()))


def seal(directory: Path, component: str, *, run_id: str = "", repository: str = "wasmerio/wasmer-sdk",
         root: Path = ROOT) -> None:
    value = version(component, root)
    require(bool(re.fullmatch(r"[\w.-]+/[\w.-]+", repository)), "Invalid GitHub repository")
    files = validate_assets(directory, component, value)
    metadata = {
        "schema": 1, "component": component, "version": value, "repository": repository,
        "tag": release_tag(component, value),
        "source_sha": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip(),
        "files": files,
    }
    if component == "swift":
        require(run_id.isdigit() and int(run_id) > 0, "Invalid Swift build workflow run ID")
        source = directory / "WasmerSDKCore.swift"
        require(source.is_file(), "Missing Swift bindings from the binary build")
        shutil.copyfile(source, root / SWIFT_SOURCE)
        source.unlink()
        metadata.update(build_run_id=int(run_id), source_sha256=source_digest(root),
                        swift_source_sha256=digest(root / SWIFT_SOURCE))
        (root / SWIFT_METADATA).write_text(json.dumps(metadata, indent=2) + "\n")
        (root / "Package.swift").write_text(swift_manifest(value, repository, files[swift_archive(value)]))
    (directory / METADATA).write_text(json.dumps(metadata, indent=2) + "\n")
    (directory / "SHA256SUMS").write_text(checksums({**files, METADATA: digest(directory / METADATA)}))
    verify(directory, component, root=root)


def verify_swift_inputs(root: Path = ROOT) -> dict:
    value = version("swift", root)
    require((root / SWIFT_METADATA).is_file(),
            "Swift release artifacts are not prepared yet. Wait for Prepare Swift release to finish; "
            "it commits the binary checksum and reruns CI automatically.")
    metadata = read_json(root / SWIFT_METADATA)
    require(metadata["schema"] == 1 and metadata["version"] == value, "Stale Swift release preparation")
    require(metadata["source_sha256"] == source_digest(root),
            "Swift release inputs changed after the build. Update the release PR and prepare it again before merging.")
    require(metadata["swift_source_sha256"] == digest(root / SWIFT_SOURCE),
            "Generated Swift bindings changed after the build")
    expected = swift_manifest(value, metadata["repository"], metadata["files"][swift_archive(value)])
    require((root / "Package.swift").read_text() == expected, "SwiftPM URL/checksum differs from release artifacts")
    return metadata


def refresh_swift(directory: Path, ref: str, root: Path = ROOT) -> None:
    """Attach tested generated files to an updated PR with identical build inputs.

    The caller fetches the release branch first, then commits and pushes normally.
    A non-fast-forward push still rejects a concurrent update after this check.
    """
    verify(directory, "swift", root=root)
    generated = sorted(GENERATED)

    def git(*args: str) -> str:
        return subprocess.check_output(["git", *args], cwd=root, text=True).strip()

    # Save only the generated files, leaving unrelated PR changes to the new ref.
    git("add", "--", *generated)
    prepared = git("write-tree")
    git("restore", "--source=HEAD", "--staged", "--worktree", "--", *generated)
    git("checkout", "--detach", ref)
    git("restore", f"--source={prepared}", "--staged", "--worktree", "--", *generated)
    # Verify before committing: a new SHA is fine, changed Swift inputs are not.
    verify(directory, "swift", root=root)


def verify(directory: Path, component: str, *, root: Path = ROOT, tag: str | None = None) -> dict:
    value = version(component, root, tag)
    metadata = read_json(directory / METADATA)
    require(metadata["schema"] == 1 and metadata["component"] == component
            and metadata["version"] == value and metadata["tag"] == release_tag(component, value),
            "Release bundle identity differs from the checked-out source")
    files = validate_assets(directory, component, value)
    require(files == metadata["files"], "Artifact checksums differ from release metadata")
    if component == "swift":
        require(metadata == verify_swift_inputs(root), "Swift release manifests differ")
    else:
        sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip()
        require(metadata["source_sha"] == sha, "Artifacts were built from a different commit")
    require((directory / "SHA256SUMS").read_text() == checksums({**files, METADATA: digest(directory / METADATA)}),
            "SHA256SUMS differs from release metadata")
    require({p.name for p in directory.iterdir()} == {*files, METADATA, "SHA256SUMS"},
            "Unexpected files in release bundle")
    return metadata


def archive_swift(directory: Path, root: Path = ROOT) -> None:
    value = version("swift", root)
    directory.mkdir(parents=True, exist_ok=True)
    framework = root / "swift/Artifacts/WasmerSDKFFI.xcframework"
    require(framework.is_dir(), "Build the universal XCFramework first")
    with zipfile.ZipFile(directory / swift_archive(value), "w", zipfile.ZIP_DEFLATED,
                         compresslevel=9) as archive:
        for path in sorted(framework.rglob("*")):
            if path.is_file():
                info = zipfile.ZipInfo(str(path.relative_to(framework.parent)), (2020, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                info.external_attr = 0o100644 << 16
                with path.open("rb") as source, archive.open(info, "w", force_zip64=True) as dest:
                    shutil.copyfileobj(source, dest)
    shutil.copyfile(root / SWIFT_SOURCE, directory / "WasmerSDKCore.swift")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("check", "archive-swift", "seal", "verify", "verify-swift-inputs", "refresh-swift"))
    parser.add_argument("--component", choices=("js", "python", "swift"), default="swift")
    parser.add_argument("--assets", type=Path)
    parser.add_argument("--tag")
    parser.add_argument("--ref", help="Fetched release PR ref for refresh-swift")
    parser.add_argument("--run-id", default=os.environ.get("GITHUB_RUN_ID", ""))
    parser.add_argument("--repository", default=os.environ.get("GITHUB_REPOSITORY", "wasmerio/wasmer-sdk"))
    args = parser.parse_args()
    if args.command == "check":
        print(version(args.component, tag=args.tag))
    elif args.command == "verify-swift-inputs":
        verify_swift_inputs()
    else:
        require(args.assets is not None, "--assets is required")
        if args.command == "archive-swift":
            archive_swift(args.assets)
        elif args.command == "seal":
            seal(args.assets, args.component, run_id=args.run_id, repository=args.repository)
        elif args.command == "refresh-swift":
            require(args.ref is not None, "--ref is required for refresh-swift")
            refresh_swift(args.assets, args.ref)
        else:
            verify(args.assets, args.component, tag=args.tag)


if __name__ == "__main__":
    main()
