[workspace]
members = [
    "js/bindgen",
    "rust",
    "rust/boltffi",
    "rust/uniffi",
]
default-members = ["rust"]
exclude = [
    "packages/edgejs",
    "packages/napi",
]
resolver = "2"

[patch.crates-io]
virtual-fs = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
virtual-mio = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
virtual-net = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
wasmer = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
wasmer-c-api-imports = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
wasmer-config = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
wasmer-napi = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
wasmer-package = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
wasmer-types = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
wasmer-wasix = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
wasmer-wasix-types = { git = "https://github.com/wasmerio/wasmer.git", rev = "7399a23f73d75d290010f9b9b601e2e5cc37ff23" }
