[workspace]
members = [
    "js/bindgen",
    "rust",
    "rust/boltffi",
    "rust/uniffi",
]
default-members = ["rust"]
exclude = [
    "packages/edgejs",
    "packages/napi",
]
resolver = "2"

[patch.crates-io]
virtual-fs = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
virtual-mio = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
virtual-net = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
wasmer = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
wasmer-c-api-imports = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
wasmer-config = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
wasmer-napi = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
wasmer-package = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
wasmer-types = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
wasmer-wasix = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
wasmer-wasix-types = { git = "https://github.com/wasmerio/wasmer.git", rev = "e4101323e18d07c7f8367f1de1cec7cd5eff1b74" }
