// swift-tools-version: 6.0
// Generated by .github/scripts/sdk_release.py. The release PR pins the binary checksum.
import PackageDescription

// Maintainer builds stage Web/sdk locally; release consumers use the CI archive.
let useLocalWebRuntime = Context.environment["WASMER_SDK_LOCAL_WEB_RUNTIME"] == "1"
let webRuntimeTargets: [Target] = useLocalWebRuntime ? [] : [
    .binaryTarget(name: "WasmerWKRuntime",
      url: "https://github.com/wasmerio/wasmer-sdk/releases/download/wasmer-sdk-swift-v0.6.0/WasmerWKRuntime-0.6.0.zip",
      checksum: "7b06150d05b5caf39194cbd9826dcaba1db06abdb1a6de831d1ab3fef79a842f"),
  ]

let package = Package(
  name: "WasmerSDK",
  platforms: [.macOS(.v12), .iOS("27.0")],
  products: [
    .library(name: "WasmerSDK", type: .static, targets: ["WasmerSDK"]),
  ],
  targets: [
    .binaryTarget(name: "WasmerSDKFFI", url: "https://github.com/wasmerio/wasmer-sdk/releases/download/wasmer-sdk-swift-v0.6.0/WasmerSDKFFI-0.6.0-macos-universal.zip",
      checksum: "3e97bffa3585bd6d204466e065d84e4a9d38c084b8969d2ab2efeca38ecc028c"),
    .target(
      name: "WasmerSDKCore", dependencies: [.target(name: "WasmerSDKFFI", condition: .when(platforms: [.macOS]))],
      path: "swift/Sources/WasmerSDKCore",
      linkerSettings: [
        .linkedLibrary("c++"), .linkedLibrary("iconv"), .linkedLibrary("resolv"),
        .linkedFramework("Security"), .linkedFramework("SystemConfiguration"),
        .linkedFramework("CoreFoundation"),
      ]
    ),
    .target(name: "WasmerSDK", dependencies: [
      .target(name: "WasmerSDKCore", condition: .when(platforms: [.macOS])),
      .target(name: "WasmerWKSDK", condition: .when(platforms: [.iOS])),
    ], path: "swift/Sources/WasmerSDK"),
    .target(
      name: "WasmerWKSDK", dependencies: useLocalWebRuntime ? [] : ["WasmerWKRuntime"],
      path: "swift/WasmerWKSDK/Sources/WasmerWKSDK",
      resources: [.copy("Web")]
    ),
  ] + webRuntimeTargets
)
