// swift-tools-version: 6.0
// Generated by .github/scripts/sdk_release.py. The release PR pins the binary checksum.
import PackageDescription

let package = Package(
  name: "WasmerSDK",
  platforms: [.macOS(.v12), .iOS("27.0")],
  products: [
    .library(name: "WasmerSDK", targets: ["WasmerSDK"]),
    .library(name: "WasmerWKSDK", type: .static, targets: ["WasmerWKSDK"]),
  ],
  targets: [
    .binaryTarget(name: "WasmerSDKFFI", url: "https://github.com/wasmerio/wasmer-sdk/releases/download/wasmer-sdk-swift-v0.2.1/WasmerSDKFFI-0.2.1-macos-universal.zip",
      checksum: "80dc53820844b55f52a3888f97dc67a0f547189584560e9b705e3e509f1cb5fa"),
    .target(
      name: "WasmerSDKCore", dependencies: ["WasmerSDKFFI"],
      path: "swift/Sources/WasmerSDKCore",
      linkerSettings: [
        .linkedLibrary("c++"), .linkedLibrary("iconv"), .linkedLibrary("resolv"),
        .linkedFramework("Security"), .linkedFramework("SystemConfiguration"),
        .linkedFramework("CoreFoundation"),
      ]
    ),
    .target(name: "WasmerSDK", dependencies: ["WasmerSDKCore"], path: "swift/Sources/WasmerSDK"),
    .target(
      name: "WasmerWKSDK", path: "swift/WasmerWKSDK/Sources/WasmerWKSDK",
      resources: [.copy("Web")]
    ),
  ]
)
