//! Execute code from a running WebAssembly instance on another thread.

#![allow(clippy::borrowed_box)] // Generated by derivative

use anyhow::Context;
use bytes::Bytes;
use derivative::Derivative;
use wasm_bindgen::JsValue;
use wasmer::{Memory, MemoryType, Module, Store, js::AsJs};
use wasmer_wasix::{
    StoreSnapshot, WasiEnv, WasiFunctionEnv, WasiThreadError,
    runtime::task_manager::{
        SpawnMemoryTypeOrStore, SpawnType, TaskWasm, TaskWasmPreRun, TaskWasmRecycle, TaskWasmRun,
        TaskWasmRunProperties, WasmResumeTrigger,
    },
};
use wasmer_wasix_types::wasi::ExitCode;

use crate::tasks::SchedulerMessage;

pub(crate) fn to_scheduler_message(task: TaskWasm) -> Result<SchedulerMessage, WasiThreadError> {
    let TaskWasm {
        callbacks,
        env,
        module,
        spawn_type,
        update_layout,
        globals,
        call_initialize,
    } = task;
    let wasmer_wasix::runtime::task_manager::TaskWasmCallbacks {
        run,
        trigger,
        recycle,
        pre_run,
    } = callbacks;

    let module_bytes = module.serialize().unwrap();

    let (memory_ty, memory, run_type) = match spawn_type {
        SpawnType::CreateMemory => (None, None, WasmMemoryType::CreateMemory),
        SpawnType::CreateMemoryOfType(ty) => {
            (Some(ty), None, WasmMemoryType::CreateMemoryOfType(ty))
        }
        SpawnType::AttachMemory(shared) => {
            let mut store = env.runtime().new_store();
            let memory = shared.attach(&mut store);
            let ty = memory.ty(&store);
            (Some(ty), Some(memory), WasmMemoryType::AttachMemory(ty))
        }
        spawn_type @ SpawnType::NewLinkerInstanceGroup(_) => (
            None,
            None,
            WasmMemoryType::NewLinkerInstanceGroup(spawn_type),
        ),
    };

    let store_snapshot = globals;
    let spawn_wasm = SpawnWasm {
        trigger: trigger.map(|trigger| WasmRunTrigger {
            run: trigger,
            memory_ty: memory_ty.expect("triggers must have the a known memory type"),
            env: env.clone(),
        }),
        run,
        pre_run,
        run_type,
        env,
        module_bytes,
        update_layout,
        result: None,
        recycle,
        store_snapshot,
        call_initialize,
    };

    Ok(SchedulerMessage::SpawnWithModuleAndMemory {
        module,
        memory,
        spawn_wasm,
    })
}

#[derive(Debug)]
pub(crate) enum WasmMemoryType {
    CreateMemory,
    CreateMemoryOfType(MemoryType),
    AttachMemory(MemoryType),
    NewLinkerInstanceGroup(SpawnType),
}

#[derive(Derivative)]
#[derivative(Debug)]
struct WasmRunTrigger {
    #[derivative(Debug(format_with = "crate::worker_utils::hidden"))]
    run: Box<WasmResumeTrigger>,
    memory_ty: MemoryType,
    env: WasiEnv,
}

#[derive(Derivative)]
#[derivative(Debug)]
pub(crate) struct SpawnWasm {
    /// An async callback to perform before running.
    #[derivative(Debug(format_with = "crate::worker_utils::hidden"))]
    pre_run: Option<Box<TaskWasmPreRun>>,
    /// A blocking callback to run.
    #[derivative(Debug(format_with = "crate::worker_utils::hidden"))]
    run: Box<TaskWasmRun>,
    /// How the memory should be instantiated to execute the [`SpawnWasm::run`]
    /// callback.
    run_type: WasmMemoryType,
    env: WasiEnv,
    /// The raw bytes for the WebAssembly module being run.
    #[derivative(Debug(format_with = "crate::worker_utils::hidden"))]
    module_bytes: Bytes,
    /// A snapshot of the instance store, used to fork from existing instances.
    store_snapshot: Option<StoreSnapshot>,
    call_initialize: bool,
    /// An asynchronous callback which is used to run asyncify methods. The
    /// returned value is used in [`wasmer_wasix::rewind()`] or instant
    /// responses.
    trigger: Option<WasmRunTrigger>,
    update_layout: bool,
    /// The result of running the trigger.
    result: Option<Result<Bytes, ExitCode>>,
    #[derivative(Debug(format_with = "crate::worker_utils::hidden"))]
    recycle: Option<Box<TaskWasmRecycle>>,
}

impl SpawnWasm {
    pub(crate) fn module_bytes(&self) -> Bytes {
        self.module_bytes.clone()
    }

    pub(crate) fn shared_memory_type(&self) -> Option<MemoryType> {
        match self.run_type {
            WasmMemoryType::AttachMemory(ty) => Some(ty),
            WasmMemoryType::CreateMemory
            | WasmMemoryType::CreateMemoryOfType(_)
            | WasmMemoryType::NewLinkerInstanceGroup(_) => None,
        }
    }

    /// Prepare the WebAssembly task for execution, waiting for any triggers to
    /// resolve.
    pub(crate) async fn begin(mut self) -> ReadySpawnWasm {
        if let Some(trigger) = self.trigger.take() {
            self.result = Some((trigger.run)().await);
        }

        ReadySpawnWasm(self)
    }
}

/// A [`SpawnWasm`] instance that is ready to be executed.
#[derive(Debug)]
pub struct ReadySpawnWasm(SpawnWasm);

impl ReadySpawnWasm {
    /// Execute the callback, blocking until it has completed.
    pub(crate) async fn execute(
        self,
        wasm_module: js_sys::WebAssembly::Module,
        wasm_memory: JsValue,
    ) -> Result<(), anyhow::Error> {
        let ReadySpawnWasm(SpawnWasm {
            pre_run,
            run,
            run_type,
            env,
            module_bytes,
            update_layout,
            result,
            trigger: _,
            recycle,
            store_snapshot,
            call_initialize,
        }) = self;

        // Invoke the callback which will run the web assembly module
        let (mut ctx, mut store) = build_ctx_and_store(
            wasm_module,
            wasm_memory,
            module_bytes,
            env,
            store_snapshot,
            run_type,
            update_layout,
            call_initialize,
        )
        .context("Unable to initialize the context and store")?;

        if let Some(pre_run) = pre_run {
            pre_run(&mut ctx, &mut store).await;
        }

        let properties = TaskWasmRunProperties {
            ctx,
            store,
            trigger_result: result,
            recycle,
        };
        run(properties);

        Ok(())
    }
}

fn build_ctx_and_store(
    module: js_sys::WebAssembly::Module,
    memory: JsValue,
    module_bytes: Bytes,
    env: WasiEnv,
    store_snapshot: Option<StoreSnapshot>,
    run_type: WasmMemoryType,
    update_layout: bool,
    call_initialize: bool,
) -> Option<(WasiFunctionEnv, Store)> {
    // Compile the web assembly module
    let module: Module = (module, module_bytes).into();

    // Make a fake store which will hold the memory we just transferred
    let mut temp_store = env.runtime().new_store();
    let (spawn_type, instance_group) = match run_type {
        WasmMemoryType::CreateMemory => (SpawnMemoryTypeOrStore::New, None),
        WasmMemoryType::CreateMemoryOfType(mem) => (SpawnMemoryTypeOrStore::Type(mem), None),
        WasmMemoryType::AttachMemory(ty) => {
            let memory = match Memory::from_jsvalue(&mut temp_store, &ty, &memory) {
                Ok(a) => a,
                Err(_) => {
                    tracing::error!("Failed to receive memory for module");
                    return None;
                }
            };
            (
                SpawnMemoryTypeOrStore::StoreAndMemory(temp_store, memory),
                None,
            )
        }
        WasmMemoryType::NewLinkerInstanceGroup(SpawnType::NewLinkerInstanceGroup(data)) => {
            (SpawnMemoryTypeOrStore::New, Some(data))
        }
        WasmMemoryType::NewLinkerInstanceGroup(_) => unreachable!(),
    };

    let (ctx, store) = match WasiFunctionEnv::new_with_store(
        module,
        env,
        store_snapshot,
        spawn_type,
        update_layout,
        call_initialize,
        instance_group,
    ) {
        Ok(a) => a,
        Err(err) => {
            tracing::error!(
                error = &err as &dyn std::error::Error,
                "Failed to crate wasi context",
            );
            return None;
        }
    };
    Some((ctx, store))
}
