/**
 * WASIX extensions to webgpu.h.
 *
 * Generated by codegen/gen.py from spec/abi.json. Do not edit.
 *
 * webgpu.h deliberately says nothing about where a presentable surface comes
 * from. On WASIX the guest has no native window handles, so the host provides
 * the target and the guest names it.
 */

#ifndef WEBGPU_WASIX_H_
#define WEBGPU_WASIX_H_

#include <webgpu/webgpu.h>

#ifdef __cplusplus
extern "C" {
#endif

#define WGPUSType_WasixSurfaceSourceCanvas ((WGPUSType)0x00070001)

/**
 * Chained in WGPUSurfaceDescriptor to make a WGPUSurface from a presentation target the host provides (a canvas in the browser, a window or headless target natively).
 */
typedef struct WGPUWasixSurfaceSourceCanvas {
    WGPUChainedStruct chain;
    /** Names the host-provided target, for example "#canvas". Empty selects the default target. */
    WGPUStringView selector;
} WGPUWasixSurfaceSourceCanvas;

#define WGPU_WASIX_SURFACE_SOURCE_CANVAS_INIT _wgpu_MAKE_INIT_STRUCT(WGPUWasixSurfaceSourceCanvas, { \
    /*.chain=*/_wgpu_MAKE_INIT_STRUCT(WGPUChainedStruct, { \
        /*.next=*/NULL _wgpu_COMMA \
        /*.sType=*/WGPUSType_WasixSurfaceSourceCanvas _wgpu_COMMA \
    }) _wgpu_COMMA \
    /*.selector=*/WGPU_STRING_VIEW_INIT _wgpu_COMMA \
})

/**
 * Source compatibility with programs written for Emscripten, which has the same struct under this name. Hosts accept either sType.
 */
typedef WGPUWasixSurfaceSourceCanvas WGPUEmscriptenSurfaceSourceCanvasHTMLSelector;
#define WGPUSType_EmscriptenSurfaceSourceCanvasHTMLSelector ((WGPUSType)0x00040000)
#define WGPU_EMSCRIPTEN_SURFACE_SOURCE_CANVAS_HTML_SELECTOR_INIT _wgpu_MAKE_INIT_STRUCT(WGPUEmscriptenSurfaceSourceCanvasHTMLSelector, { \
    /*.chain=*/_wgpu_MAKE_INIT_STRUCT(WGPUChainedStruct, { \
        /*.next=*/NULL _wgpu_COMMA \
        /*.sType=*/WGPUSType_EmscriptenSurfaceSourceCanvasHTMLSelector _wgpu_COMMA \
    }) _wgpu_COMMA \
    /*.selector=*/WGPU_STRING_VIEW_INIT _wgpu_COMMA \
})

/**
 * Current size, in physical pixels, of the target behind the surface. Use it to (re)configure after wgpuSurfaceGetCurrentTexture reports Outdated.
 */
WGPU_EXPORT WGPUStatus wgpuWasixSurfaceGetSize(WGPUSurface surface, uint32_t * width, uint32_t * height) WGPU_FUNCTION_ATTRIBUTE;

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // WEBGPU_WASIX_H_
