// Package wasmer_sdk_uniffi is generated by UniFFI; this file supplies linker configuration.
package wasmer_sdk_uniffi

// Native library selection and its system dependencies are supplied by the
// wasmer-sdk helper through CGO_LDFLAGS, or by go/scripts/test.py locally.

// #cgo CFLAGS: -I${SRCDIR}
import "C"
