// Generated by codegen/gen.py from spec/gui.json and spec/keys.json. Do not edit.

/**
 * <wasmer/gui.h>
 *
 * Windows, input, text entry and the clipboard for WASIX programs.
 *
 * A program creates an instance, opens windows on it, and drains the instance's event queue.
 * The host never calls into the program: everything it has to say arrives as an event record,
 * and everything a platform wants answered on the spot is declared ahead of time.
 *
 * Every function returns a WGUIStatus (or nothing) and hands values back through out-pointers.
 * A host that does not have a function answers WGUIStatus_Unimplemented and does nothing, so a
 * program built against a newer header still starts on an older host.
 *
 * All functions may be called from any thread. Sizes and positions are physical pixels unless
 * stated otherwise.
 */

#ifndef WASMER_GUI_H_
#define WASMER_GUI_H_

#include <stddef.h>
#include <stdint.h>

/** Every function below is a WebAssembly import of this module: there is no library to link. */
#define WGUI_IMPORT_MODULE "wasmer_gui_v0"
#if defined(__wasm__)
#  define WGUI_IMPORT(name) __attribute__((import_module(WGUI_IMPORT_MODULE), import_name(#name)))
#else
#  define WGUI_IMPORT(name)
#endif

#if defined(__cplusplus)
#  define WGUI_COMMA ,
#  if __cplusplus >= 201103L
#    define WGUI_MAKE_INIT_STRUCT(type, value) (type value)
#  else
#    define WGUI_MAKE_INIT_STRUCT(type, value) value
#  endif
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
#  define WGUI_COMMA ,
#  define WGUI_MAKE_INIT_STRUCT(type, value) ((type) value)
#else
#  define WGUI_COMMA ,
#  define WGUI_MAKE_INIT_STRUCT(type, value) value
#endif

// -- Constants ------------------------------------------------------------

/**
 * The version of this header: major << 16 | minor. WGUI_INSTANCE_DESCRIPTOR_INIT passes it to
 * the host, which behaves as that version describes.
 */
#define WGUI_ABI_VERSION (0x00000001U)

/**
 * No event record is larger. A buffer handed to wguiInstancePollEvents must hold at least this
 * many bytes.
 */
#define WGUI_MAX_EVENT_SIZE (8192)

/** As a string length: the string is NUL-terminated. */
#define WGUI_STRLEN (SIZE_MAX)

/** As a timeout: no timeout. */
#define WGUI_WAIT_FOREVER (UINT64_MAX)

/** A window position the host does not know or does not tell (Wayland, a browser). */
#define WGUI_POSITION_UNDEFINED (INT32_MIN)

/** As a composition's selection: the input method shows no cursor. */
#define WGUI_NO_TEXT_CURSOR (UINT32_MAX)

/**
 * Set in a chained struct's sType when ignoring it would be wrong. A host that does not know
 * the struct then fails the call with WGUIStatus_Unsupported instead of skipping it.
 */
#define WGUI_STYPE_MUST_UNDERSTAND (0x80000000U)

/** The part of a WGUIKey that says what the rest means. */
#define WGUI_KEY_TAG_MASK (0xFF000000U)

/** The part of a WGUIKey its tag describes. */
#define WGUI_KEY_VALUE_MASK (0x00FFFFFFU)

/** Tag: the value is the one Unicode scalar value the key produces (0 is WGUIKey_Unidentified). */
#define WGUI_KEY_CHARACTER (0x00000000U)

/** Tag: a named key, one of the WGUIKey_* constants. */
#define WGUI_KEY_NAMED (0x01000000U)

/**
 * Tag: a dead key. The value is the combining character it adds to the next key, or 0 if
 * unknown.
 */
#define WGUI_KEY_DEAD (0x02000000U)

/**
 * Tag: the key produces more than one scalar value. The value is the first; the event's
 * keyString has all of them.
 */
#define WGUI_KEY_SEQUENCE (0x03000000U)

/** The pointer id of the mouse cursor, whichever mouse or touchpad moves it. */
#define WGUI_POINTER_ID_MOUSE (1)

// -- Basic types ----------------------------------------------------------

typedef uint32_t WGUIBool;
/** Sets of flags that have room for 64. */
typedef uint64_t WGUIFlags;

// Handles are numbers the host gives out. 0 is never a handle. A handle works on
// every thread of the program, and using one after it was destroyed is an error
// the host reports, not a crash.

/**
 * A program's connection to the window system, and its event queue. Destroying it destroys its
 * windows and cursors.
 */
typedef uint32_t WGUIInstance;

/** A screen. Displays belong to the host: there is nothing to destroy. */
typedef uint32_t WGUIDisplay;

/**
 * A window: a native top-level window, or a target the embedder provides (a canvas in a
 * browser, a view in an app).
 */
typedef uint32_t WGUIWindow;

/** A cursor image. */
typedef uint32_t WGUICursor;

/**
 * A string that need not end in NUL: `length` bytes at `data`, or up to the first NUL when
 * `length` is WGUI_STRLEN. UTF-8.
 */
typedef struct WGUIStringView {
    const char* data;
    size_t length;
} WGUIStringView;

#define WGUI_STRING_VIEW_INIT WGUI_MAKE_INIT_STRUCT(WGUIStringView, { \
    /*.data=*/NULL WGUI_COMMA \
    /*.length=*/WGUI_STRLEN \
})

// -- Enumerations ---------------------------------------------------------

/** What a function did. Out-values are written only on Success, unless a status says otherwise. */
typedef enum WGUIStatus {
    /** The host does not have this function. Nothing was done and nothing was written. */
    WGUIStatus_Unimplemented = 0x00000000,
    /** Done, or the request was accepted. */
    WGUIStatus_Success = 0x00000001,
    /** The host failed. */
    WGUIStatus_Error = 0x00000002,
    /**
     * The host knows this, but cannot do it here: the platform lacks it or the feature is not
     * enabled.
     */
    WGUIStatus_Unsupported = 0x00000003,
    /**
     * An enum value, a struct, a chain, a string that is not UTF-8, a missing pointer, or a
     * reserved field that is not zero.
     */
    WGUIStatus_InvalidArgument = 0x00000004,
    /** A handle that is null, stale or of another type. */
    WGUIStatus_InvalidHandle = 0x00000005,
    /** The size needed was written; nothing else was. */
    WGUIStatus_BufferTooSmall = 0x00000006,
    /** The answer needs a request first. */
    WGUIStatus_Pending = 0x00000007,
    /** The user, a permission or the embedder's policy said no. */
    WGUIStatus_Denied = 0x00000008,
    /** A limit set by the embedder was reached. */
    WGUIStatus_LimitExceeded = 0x00000009,
    /** No such target, or nothing of that type. */
    WGUIStatus_NotFound = 0x0000000A,
    /** The target is already in use by another window. */
    WGUIStatus_Busy = 0x0000000B,
    /** The window's host side is gone. */
    WGUIStatus_Lost = 0x0000000C,
    /** A request was replaced by a later one, or what it was for was destroyed. */
    WGUIStatus_Cancelled = 0x0000000D,
    WGUIStatus_Force32 = 0x7FFFFFFF
} WGUIStatus;

/**
 * Identifies a struct in a nextInChain list. This version defines none; hosts skip the ones
 * they do not know unless WGUI_STYPE_MUST_UNDERSTAND is set.
 */
typedef enum WGUISType {
    /** Not a struct type. */
    WGUISType_Invalid = 0x00000000,
    WGUISType_Force32 = 0x7FFFFFFF
} WGUISType;

/** Something a host may or may not offer. Query with wguiHasFeature. */
typedef enum WGUIFeatureName {
    /** Windows can be created at all. */
    WGUIFeatureName_Windows = 0x00000001,
    /**
     * Windows beyond the targets the embedder provides: real top-level windows, as many as the
     * embedder's limit allows.
     */
    WGUIFeatureName_TopLevelWindows = 0x00000002,
    /** Window positions are known and can be set. */
    WGUIFeatureName_WindowPosition = 0x00000003,
    /** Minimize, maximize, borders and level can be changed. */
    WGUIFeatureName_WindowStates = 0x00000004,
    /** Fullscreen at the display's own mode. */
    WGUIFeatureName_FullscreenBorderless = 0x00000005,
    /** Fullscreen with a display mode of the program's choice. */
    WGUIFeatureName_FullscreenExclusive = 0x00000006,
    /** Displays are listed with real geometry. */
    WGUIFeatureName_Displays = 0x00000007,
    /** Input methods: composition and committed text. */
    WGUIFeatureName_TextInput = 0x00000008,
    /** An on-screen keyboard can be shown and hidden. */
    WGUIFeatureName_ScreenKeyboard = 0x00000009,
    /** Touch contacts are reported as pointers. */
    WGUIFeatureName_Touch = 0x0000000A,
    /** Pens are reported as pointers, with pressure and tilt where the hardware has them. */
    WGUIFeatureName_Pen = 0x0000000B,
    /** The WGUIEventClass_Raw events. */
    WGUIFeatureName_RawInput = 0x0000000C,
    /** Raw events arrive while no window of the program has focus. */
    WGUIFeatureName_RawInputUnfocused = 0x0000000D,
    /** wguiWindowSetCursorShape. */
    WGUIFeatureName_CursorShapes = 0x0000000E,
    /** wguiInstanceCreateCursor. */
    WGUIFeatureName_CustomCursors = 0x0000000F,
    /** wguiWindowSetCursorPosition. */
    WGUIFeatureName_CursorWarp = 0x00000010,
    /** WGUICursorGrab_Confined. */
    WGUIFeatureName_CursorConfine = 0x00000011,
    /** WGUICursorGrab_Locked. */
    WGUIFeatureName_CursorLock = 0x00000012,
    /** Text can be written to the clipboard, and read if the embedder allows. */
    WGUIFeatureName_ClipboardText = 0x00000013,
    /** wguiInstanceReadClipboard never answers WGUIStatus_Pending. */
    WGUIFeatureName_ClipboardSyncRead = 0x00000014,
    /** Light or dark appearance is known. */
    WGUIFeatureName_Theme = 0x00000015,
    /** wguiWindowRequestAttention. */
    WGUIFeatureName_AttentionRequest = 0x00000016,
    /** Reserved: clipboard content other than text. */
    WGUIFeatureName_ClipboardData = 0x00000017,
    /** Reserved: WGUIClipboardSelection_Primary. */
    WGUIFeatureName_PrimarySelection = 0x00000018,
    /** Reserved: pinch, rotate and pan gestures. */
    WGUIFeatureName_Gestures = 0x00000019,
    /** Reserved: the layout's key map. */
    WGUIFeatureName_KeyboardLayout = 0x0000001A,
    /** Reserved: text around the caret for input methods. */
    WGUIFeatureName_TextSurrounding = 0x0000001B,
    /** Reserved: dragging to and from windows. */
    WGUIFeatureName_DragAndDrop = 0x0000001C,
    /** wguiWindowPresentPixels: showing frames the program drew itself, without a GPU. */
    WGUIFeatureName_PixelPresent = 0x0000001D,
    /** Reserved: a file descriptor that becomes readable when events are queued. */
    WGUIFeatureName_EventFd = 0x0000001E,
    /** Reserved: game controllers. */
    WGUIFeatureName_Gamepads = 0x0000001F,
    WGUIFeatureName_Force32 = 0x7FFFFFFF
} WGUIFeatureName;

/** What is behind the window system. */
typedef enum WGUIHostKind {
    WGUIHostKind_Unknown = 0x00000000,
    /** No screen: windows exist, and input comes from whoever embeds the program. */
    WGUIHostKind_Headless = 0x00000001,
    /** A desktop window system. */
    WGUIHostKind_Desktop = 0x00000002,
    /** A web page: windows are canvases. */
    WGUIHostKind_Browser = 0x00000003,
    /** A phone or tablet. */
    WGUIHostKind_Mobile = 0x00000004,
    /** Views inside another application. */
    WGUIHostKind_Embedded = 0x00000005,
    WGUIHostKind_Force32 = 0x7FFFFFFF
} WGUIHostKind;

/** Light or dark appearance. */
typedef enum WGUITheme {
    WGUITheme_Unknown = 0x00000000,
    WGUITheme_Light = 0x00000001,
    WGUITheme_Dark = 0x00000002,
    WGUITheme_Force32 = 0x7FFFFFFF
} WGUITheme;

/** Which function a WGUIEventType_RequestCompleted answers. */
typedef enum WGUIRequestKind {
    /** wguiWindowSetFullscreen */
    WGUIRequestKind_Fullscreen = 0x00000001,
    /** wguiWindowSetCursorGrab */
    WGUIRequestKind_CursorGrab = 0x00000002,
    /** wguiInstanceRequestClipboard */
    WGUIRequestKind_ClipboardRequest = 0x00000003,
    /** wguiInstanceWriteClipboard */
    WGUIRequestKind_ClipboardWrite = 0x00000004,
    WGUIRequestKind_Force32 = 0x7FFFFFFF
} WGUIRequestKind;

typedef enum WGUIFullscreenMode {
    /** Not fullscreen. */
    WGUIFullscreenMode_None = 0x00000000,
    /** The window covers the display at its current mode. */
    WGUIFullscreenMode_Borderless = 0x00000001,
    /** The display switches mode for the window. Needs WGUIFeatureName_FullscreenExclusive. */
    WGUIFullscreenMode_Exclusive = 0x00000002,
    WGUIFullscreenMode_Force32 = 0x7FFFFFFF
} WGUIFullscreenMode;

typedef enum WGUIAttentionLevel {
    /** Stop asking. */
    WGUIAttentionLevel_None = 0x00000000,
    /** Once, gently. */
    WGUIAttentionLevel_Informational = 0x00000001,
    /** Until the user responds. */
    WGUIAttentionLevel_Critical = 0x00000002,
    WGUIAttentionLevel_Force32 = 0x7FFFFFFF
} WGUIAttentionLevel;

typedef enum WGUICursorGrab {
    /** The cursor is free. */
    WGUICursorGrab_None = 0x00000000,
    /** The cursor stays inside the window. */
    WGUICursorGrab_Confined = 0x00000001,
    /**
     * The cursor is hidden and stays where it was. Pointer events keep that position and carry
     * the movement in deltaX and deltaY.
     */
    WGUICursorGrab_Locked = 0x00000002,
    WGUICursorGrab_Force32 = 0x7FFFFFFF
} WGUICursorGrab;

/** Why a window's cursor grab changed. */
typedef enum WGUICursorGrabReason {
    /** The program asked. */
    WGUICursorGrabReason_Requested = 0x00000001,
    /** The user ended it (Escape in a browser). */
    WGUICursorGrabReason_User = 0x00000002,
    /** The window lost focus. The host grabs again when focus returns. */
    WGUICursorGrabReason_FocusLost = 0x00000003,
    /** The grab came back with focus. */
    WGUICursorGrabReason_FocusGained = 0x00000004,
    /** The host or the embedder took it away. */
    WGUICursorGrabReason_Host = 0x00000005,
    WGUICursorGrabReason_Force32 = 0x7FFFFFFF
} WGUICursorGrabReason;

/** The system's cursors, named as in CSS. */
typedef enum WGUICursorShape {
    WGUICursorShape_Default = 0x00000001,
    WGUICursorShape_ContextMenu = 0x00000002,
    WGUICursorShape_Help = 0x00000003,
    WGUICursorShape_Pointer = 0x00000004,
    WGUICursorShape_Progress = 0x00000005,
    WGUICursorShape_Wait = 0x00000006,
    WGUICursorShape_Cell = 0x00000007,
    WGUICursorShape_Crosshair = 0x00000008,
    WGUICursorShape_Text = 0x00000009,
    WGUICursorShape_VerticalText = 0x0000000A,
    WGUICursorShape_Alias = 0x0000000B,
    WGUICursorShape_Copy = 0x0000000C,
    WGUICursorShape_Move = 0x0000000D,
    WGUICursorShape_NoDrop = 0x0000000E,
    WGUICursorShape_NotAllowed = 0x0000000F,
    WGUICursorShape_Grab = 0x00000010,
    WGUICursorShape_Grabbing = 0x00000011,
    WGUICursorShape_EResize = 0x00000012,
    WGUICursorShape_NResize = 0x00000013,
    WGUICursorShape_NeResize = 0x00000014,
    WGUICursorShape_NwResize = 0x00000015,
    WGUICursorShape_SResize = 0x00000016,
    WGUICursorShape_SeResize = 0x00000017,
    WGUICursorShape_SwResize = 0x00000018,
    WGUICursorShape_WResize = 0x00000019,
    WGUICursorShape_EwResize = 0x0000001A,
    WGUICursorShape_NsResize = 0x0000001B,
    WGUICursorShape_NeswResize = 0x0000001C,
    WGUICursorShape_NwseResize = 0x0000001D,
    WGUICursorShape_ColResize = 0x0000001E,
    WGUICursorShape_RowResize = 0x0000001F,
    WGUICursorShape_AllScroll = 0x00000020,
    WGUICursorShape_ZoomIn = 0x00000021,
    WGUICursorShape_ZoomOut = 0x00000022,
    WGUICursorShape_Force32 = 0x7FFFFFFF
} WGUICursorShape;

typedef enum WGUIClipboardSelection {
    /** What copy and paste use. */
    WGUIClipboardSelection_Clipboard = 0x00000001,
    /**
     * The selection X11 and Wayland paste with the middle button. Needs
     * WGUIFeatureName_PrimarySelection.
     */
    WGUIClipboardSelection_Primary = 0x00000002,
    WGUIClipboardSelection_Force32 = 0x7FFFFFFF
} WGUIClipboardSelection;

/** What a text field is for. Hosts use it to choose a keyboard and to switch helpers off. */
typedef enum WGUITextInputPurpose {
    WGUITextInputPurpose_Normal = 0x00000000,
    WGUITextInputPurpose_Password = 0x00000001,
    WGUITextInputPurpose_Terminal = 0x00000002,
    WGUITextInputPurpose_Number = 0x00000003,
    WGUITextInputPurpose_Phone = 0x00000004,
    WGUITextInputPurpose_Url = 0x00000005,
    WGUITextInputPurpose_Email = 0x00000006,
    WGUITextInputPurpose_Pin = 0x00000007,
    WGUITextInputPurpose_Date = 0x00000008,
    WGUITextInputPurpose_Time = 0x00000009,
    WGUITextInputPurpose_Name = 0x0000000A,
    WGUITextInputPurpose_Username = 0x0000000B,
    WGUITextInputPurpose_Search = 0x0000000C,
    WGUITextInputPurpose_Force32 = 0x7FFFFFFF
} WGUITextInputPurpose;

typedef enum WGUIScreenKeyboardPolicy {
    /** Shown when there is no hardware keyboard. */
    WGUIScreenKeyboardPolicy_Auto = 0x00000000,
    WGUIScreenKeyboardPolicy_Show = 0x00000001,
    WGUIScreenKeyboardPolicy_Hide = 0x00000002,
    WGUIScreenKeyboardPolicy_Force32 = 0x7FFFFFFF
} WGUIScreenKeyboardPolicy;

/** Which of several keys with the same meaning. */
typedef enum WGUIKeyLocation {
    WGUIKeyLocation_Standard = 0x00000000,
    WGUIKeyLocation_Left = 0x00000001,
    WGUIKeyLocation_Right = 0x00000002,
    WGUIKeyLocation_Numpad = 0x00000003,
    WGUIKeyLocation_Force32 = 0x7FFFFFFF
} WGUIKeyLocation;

typedef enum WGUIPointerKind {
    /**
     * The mouse cursor: every mouse and touchpad together, always pointer id
     * WGUI_POINTER_ID_MOUSE.
     */
    WGUIPointerKind_Mouse = 0x00000001,
    /** One finger. Its id lasts from WGUIEventType_PointerDown to PointerUp or PointerCancel. */
    WGUIPointerKind_Touch = 0x00000002,
    /** A pen. Its id lasts from PointerEnter to PointerLeave. */
    WGUIPointerKind_Pen = 0x00000003,
    WGUIPointerKind_Force32 = 0x7FFFFFFF
} WGUIPointerKind;

/** Values above Forward are further buttons of the device, numbered on. */
typedef enum WGUIPointerButton {
    /** No button changed (motion, enter, leave). */
    WGUIPointerButton_None = 0x00000000,
    /** The left mouse button, a touch contact, a pen's tip. */
    WGUIPointerButton_Primary = 0x00000001,
    /** The right mouse button, a pen's barrel button. */
    WGUIPointerButton_Secondary = 0x00000002,
    /** The middle mouse button. */
    WGUIPointerButton_Auxiliary = 0x00000003,
    WGUIPointerButton_Back = 0x00000004,
    WGUIPointerButton_Forward = 0x00000005,
    /** A pen's eraser end. */
    WGUIPointerButton_Eraser = 0x00000006,
    WGUIPointerButton_Force32 = 0x7FFFFFFF
} WGUIPointerButton;

typedef enum WGUIPointerTool {
    WGUIPointerTool_Unknown = 0x00000000,
    WGUIPointerTool_Pen = 0x00000001,
    WGUIPointerTool_Eraser = 0x00000002,
    WGUIPointerTool_Force32 = 0x7FFFFFFF
} WGUIPointerTool;

typedef enum WGUIWheelUnit {
    /** Notches of a wheel. */
    WGUIWheelUnit_Line = 0x00000001,
    /** Physical pixels, from a touchpad or a precise wheel. */
    WGUIWheelUnit_Pixel = 0x00000002,
    WGUIWheelUnit_Force32 = 0x7FFFFFFF
} WGUIWheelUnit;

/** Where a wheel record stands in a scroll gesture. */
typedef enum WGUIWheelPhase {
    /** A plain wheel: no gesture. */
    WGUIWheelPhase_None = 0x00000000,
    WGUIWheelPhase_Began = 0x00000001,
    WGUIWheelPhase_Changed = 0x00000002,
    WGUIWheelPhase_Ended = 0x00000003,
    WGUIWheelPhase_Cancelled = 0x00000004,
    WGUIWheelPhase_Force32 = 0x7FFFFFFF
} WGUIWheelPhase;

/**
 * How a pixel of a frame for wguiWindowPresentPixels lies in memory: four bytes, 8 bits a
 * channel.
 */
typedef enum WGUIPixelFormat {
    /**
     * Blue, green, red, alpha: 0xAARRGGBB read as a little-endian 32-bit number, which is how
     * most software renderers keep their pixels.
     */
    WGUIPixelFormat_Bgra8 = 0x00000001,
    /** Red, green, blue, alpha. */
    WGUIPixelFormat_Rgba8 = 0x00000002,
    WGUIPixelFormat_Force32 = 0x7FFFFFFF
} WGUIPixelFormat;

/** What the fourth byte of a pixel means. */
typedef enum WGUIPixelAlpha {
    /** Nothing: every pixel covers what is behind the window, whatever the byte holds. */
    WGUIPixelAlpha_Opaque = 0x00000001,
    /**
     * How much the pixel covers, with the colours already multiplied by it. Shows through only
     * in a window made with WGUIWindowFlags_Transparent, on hosts that have such windows.
     */
    WGUIPixelAlpha_Premultiplied = 0x00000002,
    /** How much the pixel covers, with the colours as they are. */
    WGUIPixelAlpha_Straight = 0x00000003,
    WGUIPixelAlpha_Force32 = 0x7FFFFFFF
} WGUIPixelAlpha;

/** What an event record is. The high byte is its class. */
typedef enum WGUIEventType {
    /** Record: WGUIEventsLostEvent. */
    WGUIEventType_EventsLost = 0x00000101,
    /** Record: WGUIRequestCompletedEvent. */
    WGUIEventType_RequestCompleted = 0x00000102,
    /**
     * The program is no longer in front of the user (a phone's home screen, a hidden tab). Its
     * windows may be unusable until it resumes. Header only.
     */
    WGUIEventType_AppSuspended = 0x00000201,
    /** Header only. */
    WGUIEventType_AppResumed = 0x00000202,
    /** The user asked the whole program to quit. It decides whether to. Header only. */
    WGUIEventType_AppQuitRequested = 0x00000203,
    /** The program is about to be stopped whatever it does. Save now. Header only. */
    WGUIEventType_AppTerminating = 0x00000204,
    /** The system switched between light and dark. Record: WGUIThemeEvent. */
    WGUIEventType_AppThemeChanged = 0x00000205,
    /** A display was added, removed or changed. List them again. Header only. */
    WGUIEventType_DisplaysChanged = 0x00000301,
    /** Record: WGUIWindowResizedEvent. */
    WGUIEventType_WindowResized = 0x00000401,
    /** Record: WGUIWindowMovedEvent. */
    WGUIEventType_WindowMoved = 0x00000402,
    /** Record: WGUIWindowFlagsChangedEvent. */
    WGUIEventType_WindowFlagsChanged = 0x00000403,
    /** Header only. */
    WGUIEventType_WindowFocusGained = 0x00000404,
    /** Comes after the synthetic releases of the keys that were down. Header only. */
    WGUIEventType_WindowFocusLost = 0x00000405,
    /**
     * The user asked to close the window. Nothing has happened to it: the program destroys it,
     * or asks the user first, or carries on. Header only.
     */
    WGUIEventType_WindowCloseRequested = 0x00000406,
    /**
     * The window should be drawn again: the program asked with wguiWindowRequestRedraw, or the
     * system uncovered it. A new window is not asked: its first WGUIEventType_WindowResized is
     * when to draw it for the first time. Header only.
     */
    WGUIEventType_WindowRedrawRequested = 0x00000407,
    /** Record: WGUIWindowDisplayChangedEvent. */
    WGUIEventType_WindowDisplayChanged = 0x00000408,
    /** Record: WGUIThemeEvent. */
    WGUIEventType_WindowThemeChanged = 0x00000409,
    /** Record: WGUIWindowCursorGrabChangedEvent. */
    WGUIEventType_WindowCursorGrabChanged = 0x0000040A,
    /**
     * The window's host side is gone (the embedder removed its target). The handle only remains
     * to be destroyed. Header only.
     */
    WGUIEventType_WindowLost = 0x0000040C,
    /** Record: WGUIKeyEvent. */
    WGUIEventType_KeyDown = 0x00000501,
    /** Record: WGUIKeyEvent. */
    WGUIEventType_KeyUp = 0x00000502,
    /** Record: WGUIModifiersChangedEvent. */
    WGUIEventType_ModifiersChanged = 0x00000503,
    /** Record: WGUITextInputStateEvent. */
    WGUIEventType_TextInputState = 0x00000601,
    /** Record: WGUITextCompositionEvent. */
    WGUIEventType_TextComposition = 0x00000602,
    /** Record: WGUITextCommitEvent. */
    WGUIEventType_TextCommit = 0x00000603,
    /** Record: WGUIPointerEvent. */
    WGUIEventType_PointerEnter = 0x00000701,
    /** Record: WGUIPointerEvent. */
    WGUIEventType_PointerLeave = 0x00000702,
    /** Record: WGUIPointerEvent. */
    WGUIEventType_PointerMotion = 0x00000703,
    /** Record: WGUIPointerEvent. */
    WGUIEventType_PointerDown = 0x00000704,
    /** Record: WGUIPointerEvent. */
    WGUIEventType_PointerUp = 0x00000705,
    /** Record: WGUIPointerEvent. */
    WGUIEventType_PointerCancel = 0x00000706,
    /** Record: WGUIWheelEvent. */
    WGUIEventType_Wheel = 0x00000801,
    /** Record: WGUIRawMotionEvent. */
    WGUIEventType_RawMotion = 0x00000901,
    /** Record: WGUIRawButtonEvent. */
    WGUIEventType_RawButton = 0x00000902,
    /** Record: WGUIRawWheelEvent. */
    WGUIEventType_RawWheel = 0x00000903,
    /** Record: WGUIRawKeyEvent. */
    WGUIEventType_RawKey = 0x00000904,
    /** Record: WGUIClipboardChangedEvent. */
    WGUIEventType_ClipboardChanged = 0x00000B01,
    WGUIEventType_Force32 = 0x7FFFFFFF
} WGUIEventType;

/**
 * A key by where it is on the keyboard, whatever the layout prints on it: the KeyboardEvent
 * `code` values of the W3C UI Events specification. Each number is the key's USB HID usage,
 * page << 16 | id (page 0x07 is the keyboard page, whose ids are also SDL's scancodes); keys
 * without a usage are on page 0.
 */
typedef enum WGUIPhysicalKey {
    WGUIPhysicalKey_Unidentified = 0x00000000,
    WGUIPhysicalKey_Hyper = 0x00000010,
    WGUIPhysicalKey_Super = 0x00000011,
    WGUIPhysicalKey_FnLock = 0x00000013,
    WGUIPhysicalKey_Suspend = 0x00000014,
    WGUIPhysicalKey_Resume = 0x00000015,
    WGUIPhysicalKey_Turbo = 0x00000016,
    WGUIPhysicalKey_Sleep = 0x00010082,
    WGUIPhysicalKey_WakeUp = 0x00010083,
    WGUIPhysicalKey_Fn = 0x00010097,
    WGUIPhysicalKey_DisplayToggleIntExt = 0x000100B5,
    WGUIPhysicalKey_KeyA = 0x00070004,
    WGUIPhysicalKey_KeyB = 0x00070005,
    WGUIPhysicalKey_KeyC = 0x00070006,
    WGUIPhysicalKey_KeyD = 0x00070007,
    WGUIPhysicalKey_KeyE = 0x00070008,
    WGUIPhysicalKey_KeyF = 0x00070009,
    WGUIPhysicalKey_KeyG = 0x0007000A,
    WGUIPhysicalKey_KeyH = 0x0007000B,
    WGUIPhysicalKey_KeyI = 0x0007000C,
    WGUIPhysicalKey_KeyJ = 0x0007000D,
    WGUIPhysicalKey_KeyK = 0x0007000E,
    WGUIPhysicalKey_KeyL = 0x0007000F,
    WGUIPhysicalKey_KeyM = 0x00070010,
    WGUIPhysicalKey_KeyN = 0x00070011,
    WGUIPhysicalKey_KeyO = 0x00070012,
    WGUIPhysicalKey_KeyP = 0x00070013,
    WGUIPhysicalKey_KeyQ = 0x00070014,
    WGUIPhysicalKey_KeyR = 0x00070015,
    WGUIPhysicalKey_KeyS = 0x00070016,
    WGUIPhysicalKey_KeyT = 0x00070017,
    WGUIPhysicalKey_KeyU = 0x00070018,
    WGUIPhysicalKey_KeyV = 0x00070019,
    WGUIPhysicalKey_KeyW = 0x0007001A,
    WGUIPhysicalKey_KeyX = 0x0007001B,
    WGUIPhysicalKey_KeyY = 0x0007001C,
    WGUIPhysicalKey_KeyZ = 0x0007001D,
    WGUIPhysicalKey_Digit1 = 0x0007001E,
    WGUIPhysicalKey_Digit2 = 0x0007001F,
    WGUIPhysicalKey_Digit3 = 0x00070020,
    WGUIPhysicalKey_Digit4 = 0x00070021,
    WGUIPhysicalKey_Digit5 = 0x00070022,
    WGUIPhysicalKey_Digit6 = 0x00070023,
    WGUIPhysicalKey_Digit7 = 0x00070024,
    WGUIPhysicalKey_Digit8 = 0x00070025,
    WGUIPhysicalKey_Digit9 = 0x00070026,
    WGUIPhysicalKey_Digit0 = 0x00070027,
    WGUIPhysicalKey_Enter = 0x00070028,
    WGUIPhysicalKey_Escape = 0x00070029,
    WGUIPhysicalKey_Backspace = 0x0007002A,
    WGUIPhysicalKey_Tab = 0x0007002B,
    WGUIPhysicalKey_Space = 0x0007002C,
    WGUIPhysicalKey_Minus = 0x0007002D,
    WGUIPhysicalKey_Equal = 0x0007002E,
    WGUIPhysicalKey_BracketLeft = 0x0007002F,
    WGUIPhysicalKey_BracketRight = 0x00070030,
    WGUIPhysicalKey_Backslash = 0x00070031,
    WGUIPhysicalKey_Semicolon = 0x00070033,
    WGUIPhysicalKey_Quote = 0x00070034,
    WGUIPhysicalKey_Backquote = 0x00070035,
    WGUIPhysicalKey_Comma = 0x00070036,
    WGUIPhysicalKey_Period = 0x00070037,
    WGUIPhysicalKey_Slash = 0x00070038,
    WGUIPhysicalKey_CapsLock = 0x00070039,
    WGUIPhysicalKey_F1 = 0x0007003A,
    WGUIPhysicalKey_F2 = 0x0007003B,
    WGUIPhysicalKey_F3 = 0x0007003C,
    WGUIPhysicalKey_F4 = 0x0007003D,
    WGUIPhysicalKey_F5 = 0x0007003E,
    WGUIPhysicalKey_F6 = 0x0007003F,
    WGUIPhysicalKey_F7 = 0x00070040,
    WGUIPhysicalKey_F8 = 0x00070041,
    WGUIPhysicalKey_F9 = 0x00070042,
    WGUIPhysicalKey_F10 = 0x00070043,
    WGUIPhysicalKey_F11 = 0x00070044,
    WGUIPhysicalKey_F12 = 0x00070045,
    WGUIPhysicalKey_PrintScreen = 0x00070046,
    WGUIPhysicalKey_ScrollLock = 0x00070047,
    WGUIPhysicalKey_Pause = 0x00070048,
    WGUIPhysicalKey_Insert = 0x00070049,
    WGUIPhysicalKey_Home = 0x0007004A,
    WGUIPhysicalKey_PageUp = 0x0007004B,
    WGUIPhysicalKey_Delete = 0x0007004C,
    WGUIPhysicalKey_End = 0x0007004D,
    WGUIPhysicalKey_PageDown = 0x0007004E,
    WGUIPhysicalKey_ArrowRight = 0x0007004F,
    WGUIPhysicalKey_ArrowLeft = 0x00070050,
    WGUIPhysicalKey_ArrowDown = 0x00070051,
    WGUIPhysicalKey_ArrowUp = 0x00070052,
    WGUIPhysicalKey_NumLock = 0x00070053,
    WGUIPhysicalKey_NumpadDivide = 0x00070054,
    WGUIPhysicalKey_NumpadMultiply = 0x00070055,
    WGUIPhysicalKey_NumpadSubtract = 0x00070056,
    WGUIPhysicalKey_NumpadAdd = 0x00070057,
    WGUIPhysicalKey_NumpadEnter = 0x00070058,
    WGUIPhysicalKey_Numpad1 = 0x00070059,
    WGUIPhysicalKey_Numpad2 = 0x0007005A,
    WGUIPhysicalKey_Numpad3 = 0x0007005B,
    WGUIPhysicalKey_Numpad4 = 0x0007005C,
    WGUIPhysicalKey_Numpad5 = 0x0007005D,
    WGUIPhysicalKey_Numpad6 = 0x0007005E,
    WGUIPhysicalKey_Numpad7 = 0x0007005F,
    WGUIPhysicalKey_Numpad8 = 0x00070060,
    WGUIPhysicalKey_Numpad9 = 0x00070061,
    WGUIPhysicalKey_Numpad0 = 0x00070062,
    WGUIPhysicalKey_NumpadDecimal = 0x00070063,
    WGUIPhysicalKey_IntlBackslash = 0x00070064,
    WGUIPhysicalKey_ContextMenu = 0x00070065,
    WGUIPhysicalKey_Power = 0x00070066,
    WGUIPhysicalKey_NumpadEqual = 0x00070067,
    WGUIPhysicalKey_F13 = 0x00070068,
    WGUIPhysicalKey_F14 = 0x00070069,
    WGUIPhysicalKey_F15 = 0x0007006A,
    WGUIPhysicalKey_F16 = 0x0007006B,
    WGUIPhysicalKey_F17 = 0x0007006C,
    WGUIPhysicalKey_F18 = 0x0007006D,
    WGUIPhysicalKey_F19 = 0x0007006E,
    WGUIPhysicalKey_F20 = 0x0007006F,
    WGUIPhysicalKey_F21 = 0x00070070,
    WGUIPhysicalKey_F22 = 0x00070071,
    WGUIPhysicalKey_F23 = 0x00070072,
    WGUIPhysicalKey_F24 = 0x00070073,
    WGUIPhysicalKey_Open = 0x00070074,
    WGUIPhysicalKey_Help = 0x00070075,
    WGUIPhysicalKey_Select = 0x00070077,
    WGUIPhysicalKey_Again = 0x00070079,
    WGUIPhysicalKey_Undo = 0x0007007A,
    WGUIPhysicalKey_Cut = 0x0007007B,
    WGUIPhysicalKey_Copy = 0x0007007C,
    WGUIPhysicalKey_Paste = 0x0007007D,
    WGUIPhysicalKey_Find = 0x0007007E,
    WGUIPhysicalKey_AudioVolumeMute = 0x0007007F,
    WGUIPhysicalKey_AudioVolumeUp = 0x00070080,
    WGUIPhysicalKey_AudioVolumeDown = 0x00070081,
    WGUIPhysicalKey_NumpadComma = 0x00070085,
    WGUIPhysicalKey_IntlRo = 0x00070087,
    WGUIPhysicalKey_KanaMode = 0x00070088,
    WGUIPhysicalKey_IntlYen = 0x00070089,
    WGUIPhysicalKey_Convert = 0x0007008A,
    WGUIPhysicalKey_NonConvert = 0x0007008B,
    WGUIPhysicalKey_Lang1 = 0x00070090,
    WGUIPhysicalKey_Lang2 = 0x00070091,
    WGUIPhysicalKey_Lang3 = 0x00070092,
    WGUIPhysicalKey_Lang4 = 0x00070093,
    WGUIPhysicalKey_Lang5 = 0x00070094,
    WGUIPhysicalKey_Abort = 0x0007009B,
    WGUIPhysicalKey_Props = 0x000700A3,
    WGUIPhysicalKey_NumpadParenLeft = 0x000700B6,
    WGUIPhysicalKey_NumpadParenRight = 0x000700B7,
    WGUIPhysicalKey_NumpadBackspace = 0x000700BB,
    WGUIPhysicalKey_NumpadMemoryStore = 0x000700D0,
    WGUIPhysicalKey_NumpadMemoryRecall = 0x000700D1,
    WGUIPhysicalKey_NumpadMemoryClear = 0x000700D2,
    WGUIPhysicalKey_NumpadMemoryAdd = 0x000700D3,
    WGUIPhysicalKey_NumpadMemorySubtract = 0x000700D4,
    WGUIPhysicalKey_NumpadClear = 0x000700D8,
    WGUIPhysicalKey_NumpadClearEntry = 0x000700D9,
    WGUIPhysicalKey_ControlLeft = 0x000700E0,
    WGUIPhysicalKey_ShiftLeft = 0x000700E1,
    WGUIPhysicalKey_AltLeft = 0x000700E2,
    WGUIPhysicalKey_MetaLeft = 0x000700E3,
    WGUIPhysicalKey_ControlRight = 0x000700E4,
    WGUIPhysicalKey_ShiftRight = 0x000700E5,
    WGUIPhysicalKey_AltRight = 0x000700E6,
    WGUIPhysicalKey_MetaRight = 0x000700E7,
    WGUIPhysicalKey_BrightnessUp = 0x000C006F,
    WGUIPhysicalKey_BrightnessDown = 0x000C0070,
    WGUIPhysicalKey_MediaPlay = 0x000C00B0,
    WGUIPhysicalKey_MediaPause = 0x000C00B1,
    WGUIPhysicalKey_MediaRecord = 0x000C00B2,
    WGUIPhysicalKey_MediaFastForward = 0x000C00B3,
    WGUIPhysicalKey_MediaRewind = 0x000C00B4,
    WGUIPhysicalKey_MediaTrackNext = 0x000C00B5,
    WGUIPhysicalKey_MediaTrackPrevious = 0x000C00B6,
    WGUIPhysicalKey_MediaStop = 0x000C00B7,
    WGUIPhysicalKey_Eject = 0x000C00B8,
    WGUIPhysicalKey_MediaPlayPause = 0x000C00CD,
    WGUIPhysicalKey_MediaSelect = 0x000C0183,
    WGUIPhysicalKey_LaunchMail = 0x000C018A,
    WGUIPhysicalKey_LaunchApp2 = 0x000C0192,
    WGUIPhysicalKey_LaunchApp1 = 0x000C0194,
    WGUIPhysicalKey_LaunchControlPanel = 0x000C019F,
    WGUIPhysicalKey_SelectTask = 0x000C01A2,
    WGUIPhysicalKey_LaunchScreenSaver = 0x000C01B1,
    WGUIPhysicalKey_LaunchAssistant = 0x000C01CB,
    WGUIPhysicalKey_BrowserSearch = 0x000C0221,
    WGUIPhysicalKey_BrowserHome = 0x000C0223,
    WGUIPhysicalKey_BrowserBack = 0x000C0224,
    WGUIPhysicalKey_BrowserForward = 0x000C0225,
    WGUIPhysicalKey_BrowserStop = 0x000C0226,
    WGUIPhysicalKey_BrowserRefresh = 0x000C0227,
    WGUIPhysicalKey_BrowserFavorites = 0x000C022A,
    WGUIPhysicalKey_ZoomToggle = 0x000C0232,
    WGUIPhysicalKey_MailReply = 0x000C0289,
    WGUIPhysicalKey_MailForward = 0x000C028B,
    WGUIPhysicalKey_MailSend = 0x000C028C,
    WGUIPhysicalKey_KeyboardLayoutSelect = 0x000C029D,
    WGUIPhysicalKey_ShowAllWindows = 0x000C029F,
    WGUIPhysicalKey_NumpadHash = 0x000700CC,
    WGUIPhysicalKey_NumpadStar = 0x00000130,
    WGUIPhysicalKey_F25 = 0x00000119,
    WGUIPhysicalKey_F26 = 0x0000011A,
    WGUIPhysicalKey_F27 = 0x0000011B,
    WGUIPhysicalKey_F28 = 0x0000011C,
    WGUIPhysicalKey_F29 = 0x0000011D,
    WGUIPhysicalKey_F30 = 0x0000011E,
    WGUIPhysicalKey_F31 = 0x0000011F,
    WGUIPhysicalKey_F32 = 0x00000120,
    WGUIPhysicalKey_F33 = 0x00000121,
    WGUIPhysicalKey_F34 = 0x00000122,
    WGUIPhysicalKey_F35 = 0x00000123,
    WGUIPhysicalKey_Force32 = 0x7FFFFFFF
} WGUIPhysicalKey;

// -- Flags ----------------------------------------------------------------

/**
 * Groups of events, for choosing which ones an instance queues. An event's class is the high
 * byte of its type: the bit for it is 1 << (type >> 8).
 */
typedef WGUIFlags WGUIEventClass;
static const WGUIEventClass WGUIEventClass_None = 0x0000000000000000;
/** Lost events and completed requests. Always on. */
static const WGUIEventClass WGUIEventClass_System = 0x0000000000000002;
static const WGUIEventClass WGUIEventClass_Application = 0x0000000000000004;
static const WGUIEventClass WGUIEventClass_Display = 0x0000000000000008;
static const WGUIEventClass WGUIEventClass_Window = 0x0000000000000010;
static const WGUIEventClass WGUIEventClass_Keyboard = 0x0000000000000020;
static const WGUIEventClass WGUIEventClass_Text = 0x0000000000000040;
static const WGUIEventClass WGUIEventClass_Pointer = 0x0000000000000080;
static const WGUIEventClass WGUIEventClass_Wheel = 0x0000000000000100;
/** Device input before the window system shapes it. Off unless asked for. */
static const WGUIEventClass WGUIEventClass_Raw = 0x0000000000000200;
/** Reserved. */
static const WGUIEventClass WGUIEventClass_Gesture = 0x0000000000000400;
static const WGUIEventClass WGUIEventClass_Clipboard = 0x0000000000000800;
/** Reserved. */
static const WGUIEventClass WGUIEventClass_Drop = 0x0000000000001000;
/** Reserved. */
static const WGUIEventClass WGUIEventClass_Device = 0x0000000000002000;
/** Reserved. */
static const WGUIEventClass WGUIEventClass_Gamepad = 0x0000000000004000;
/** What WGUI_INSTANCE_DESCRIPTOR_INIT asks for. */
static const WGUIEventClass WGUIEventClass_Default = 0x00000000000009FE;

/**
 * A window's state. The low 16 bits can be asked for (at creation and with wguiWindowSetFlags);
 * the rest are only reported.
 */
typedef WGUIFlags WGUIWindowFlags;
static const WGUIWindowFlags WGUIWindowFlags_None = 0x0000000000000000;
/** Shown on screen. */
static const WGUIWindowFlags WGUIWindowFlags_Visible = 0x0000000000000001;
/** The user can resize it. */
static const WGUIWindowFlags WGUIWindowFlags_Resizable = 0x0000000000000002;
/** It has a title bar and borders. */
static const WGUIWindowFlags WGUIWindowFlags_Decorated = 0x0000000000000004;
static const WGUIWindowFlags WGUIWindowFlags_Minimized = 0x0000000000000008;
static const WGUIWindowFlags WGUIWindowFlags_Maximized = 0x0000000000000010;
static const WGUIWindowFlags WGUIWindowFlags_AlwaysOnTop = 0x0000000000000020;
static const WGUIWindowFlags WGUIWindowFlags_AlwaysOnBottom = 0x0000000000000040;
/** The window's background can show what is behind it. Only at creation. */
static const WGUIWindowFlags WGUIWindowFlags_Transparent = 0x0000000000000080;
/** Every bit a program can ask for. */
static const WGUIWindowFlags WGUIWindowFlags_Requestable = 0x000000000000FFFF;
/**
 * It has keyboard focus. Changes are announced by WGUIEventType_WindowFocusGained and
 * WindowFocusLost, not by WindowFlagsChanged.
 */
static const WGUIWindowFlags WGUIWindowFlags_Focused = 0x0000000000010000;
/**
 * The mouse cursor is over it. Changes are announced by the mouse's WGUIEventType_PointerEnter
 * and PointerLeave.
 */
static const WGUIWindowFlags WGUIWindowFlags_Hovered = 0x0000000000020000;
/** Nothing of it can be seen: drawing is wasted. */
static const WGUIWindowFlags WGUIWindowFlags_Occluded = 0x0000000000040000;
/** Changed with wguiWindowSetFullscreen. */
static const WGUIWindowFlags WGUIWindowFlags_Fullscreen = 0x0000000000080000;

/** How to read a WGUIWindowDescriptor. */
typedef uint32_t WGUIWindowOptions;
static const WGUIWindowOptions WGUIWindowOptions_None = 0x00000000;
/**
 * The descriptor's sizes, limits and position are in logical units: the host multiplies them by
 * the scale factor of the display the window opens on, which the program cannot know yet.
 */
static const WGUIWindowOptions WGUIWindowOptions_LogicalUnits = 0x00000001;
/** Place the window at the descriptor's x and y. */
static const WGUIWindowOptions WGUIWindowOptions_Positioned = 0x00000002;

typedef uint32_t WGUIFullscreenFlags;
static const WGUIFullscreenFlags WGUIFullscreenFlags_None = 0x00000000;
/** Fail with WGUIStatus_Denied instead of waiting for a user gesture. */
static const WGUIFullscreenFlags WGUIFullscreenFlags_NoDeferral = 0x00000001;

/** Why wguiInstanceWaitEvents returned. None of them: the timeout passed. */
typedef uint32_t WGUIWaitReasons;
static const WGUIWaitReasons WGUIWaitReasons_None = 0x00000000;
/** The queue has records. */
static const WGUIWaitReasons WGUIWaitReasons_Events = 0x00000001;
/** wguiInstanceWake was called. */
static const WGUIWaitReasons WGUIWaitReasons_Woken = 0x00000002;
/**
 * The host ended the wait so that the system can reach the thread. Nothing happened; wait
 * again.
 */
static const WGUIWaitReasons WGUIWaitReasons_Interrupted = 0x00000004;

typedef uint32_t WGUIEventFlags;
static const WGUIEventFlags WGUIEventFlags_None = 0x00000000;
/**
 * Made by the host to keep the program's view consistent (a key release on focus loss), not
 * caused by the user just now.
 */
static const WGUIEventFlags WGUIEventFlags_Synthetic = 0x00000001;
/** Stands for several events of the same kind that the host merged. */
static const WGUIEventFlags WGUIEventFlags_Coalesced = 0x00000002;

/** What a WGUIEventType_WindowResized changed. */
typedef uint32_t WGUIResizeFlags;
static const WGUIResizeFlags WGUIResizeFlags_None = 0x00000000;
static const WGUIResizeFlags WGUIResizeFlags_Size = 0x00000001;
static const WGUIResizeFlags WGUIResizeFlags_ScaleFactor = 0x00000002;

/**
 * Modifier keys. The low bits say what is in effect, whichever key causes it (sticky keys
 * count); the high bits say which keys are held, where the host can tell. AltGraph is reported
 * as AltGraph, not as Control and Alt.
 */
typedef uint32_t WGUIModifiers;
static const WGUIModifiers WGUIModifiers_None = 0x00000000;
static const WGUIModifiers WGUIModifiers_Shift = 0x00000001;
static const WGUIModifiers WGUIModifiers_Control = 0x00000002;
static const WGUIModifiers WGUIModifiers_Alt = 0x00000004;
/** The Windows key, Command on a Mac. */
static const WGUIModifiers WGUIModifiers_Super = 0x00000008;
static const WGUIModifiers WGUIModifiers_AltGraph = 0x00000010;
/** Caps Lock is on. */
static const WGUIModifiers WGUIModifiers_CapsLock = 0x00000100;
static const WGUIModifiers WGUIModifiers_NumLock = 0x00000200;
static const WGUIModifiers WGUIModifiers_ScrollLock = 0x00000400;
static const WGUIModifiers WGUIModifiers_LeftShift = 0x00010000;
static const WGUIModifiers WGUIModifiers_RightShift = 0x00020000;
static const WGUIModifiers WGUIModifiers_LeftControl = 0x00040000;
static const WGUIModifiers WGUIModifiers_RightControl = 0x00080000;
static const WGUIModifiers WGUIModifiers_LeftAlt = 0x00100000;
static const WGUIModifiers WGUIModifiers_RightAlt = 0x00200000;
static const WGUIModifiers WGUIModifiers_LeftSuper = 0x00400000;
static const WGUIModifiers WGUIModifiers_RightSuper = 0x00800000;

typedef uint32_t WGUIKeyFlags;
static const WGUIKeyFlags WGUIKeyFlags_None = 0x00000000;
/** The key is being held: this press repeats the last one, with no release in between. */
static const WGUIKeyFlags WGUIKeyFlags_Repeat = 0x00000001;
/** An input method took this key for the text it is composing. */
static const WGUIKeyFlags WGUIKeyFlags_Composing = 0x00000002;

typedef uint32_t WGUIPointerFlags;
static const WGUIPointerFlags WGUIPointerFlags_None = 0x00000000;
/**
 * The mouse cursor, the first finger down, or the pen. A program that handles one pointer
 * handles the records with this flag.
 */
static const WGUIPointerFlags WGUIPointerFlags_Primary = 0x00000001;
/** A button is held, the finger touches, the pen's tip is down. */
static const WGUIPointerFlags WGUIPointerFlags_InContact = 0x00000002;
/** The pressure field is measured, not assumed. */
static const WGUIPointerFlags WGUIPointerFlags_HasPressure = 0x00000004;
/** The tilt and twist fields are measured. */
static const WGUIPointerFlags WGUIPointerFlags_HasTilt = 0x00000008;

/** The buttons held: bit n - 1 for WGUIPointerButton n. */
typedef uint32_t WGUIPointerButtons;
static const WGUIPointerButtons WGUIPointerButtons_None = 0x00000000;
static const WGUIPointerButtons WGUIPointerButtons_Primary = 0x00000001;
static const WGUIPointerButtons WGUIPointerButtons_Secondary = 0x00000002;
static const WGUIPointerButtons WGUIPointerButtons_Auxiliary = 0x00000004;
static const WGUIPointerButtons WGUIPointerButtons_Back = 0x00000008;
static const WGUIPointerButtons WGUIPointerButtons_Forward = 0x00000010;
static const WGUIPointerButtons WGUIPointerButtons_Eraser = 0x00000020;

typedef uint32_t WGUIWheelFlags;
static const WGUIWheelFlags WGUIWheelFlags_None = 0x00000000;
/** The fingers have left the touchpad: the scroll is coasting. */
static const WGUIWheelFlags WGUIWheelFlags_Momentum = 0x00000001;
/** The user's "natural scrolling" setting is on. The deltas already follow it. */
static const WGUIWheelFlags WGUIWheelFlags_Inverted = 0x00000002;

typedef uint32_t WGUITextInputHints;
static const WGUITextInputHints WGUITextInputHints_None = 0x00000000;
/** Suggestions are welcome. */
static const WGUITextInputHints WGUITextInputHints_Completion = 0x00000001;
static const WGUITextInputHints WGUITextInputHints_Spellcheck = 0x00000002;
static const WGUITextInputHints WGUITextInputHints_CapitalizeSentences = 0x00000004;
static const WGUITextInputHints WGUITextInputHints_CapitalizeWords = 0x00000008;
static const WGUITextInputHints WGUITextInputHints_CapitalizeCharacters = 0x00000010;
/** The field does not show what is typed. */
static const WGUITextInputHints WGUITextInputHints_HiddenText = 0x00000020;
/** Do not learn from or store what is typed. */
static const WGUITextInputHints WGUITextInputHints_SensitiveData = 0x00000040;
/** Prefer a Latin layout. */
static const WGUITextInputHints WGUITextInputHints_Latin = 0x00000080;
/** Enter inserts a line break. */
static const WGUITextInputHints WGUITextInputHints_Multiline = 0x00000100;

typedef uint32_t WGUITextInputStateFlags;
static const WGUITextInputStateFlags WGUITextInputStateFlags_None = 0x00000000;
/** An input method is attached to the window. */
static const WGUITextInputStateFlags WGUITextInputStateFlags_Active = 0x00000001;
static const WGUITextInputStateFlags WGUITextInputStateFlags_ScreenKeyboardVisible = 0x00000002;

typedef uint32_t WGUITextFlags;
static const WGUITextFlags WGUITextFlags_None = 0x00000000;
/**
 * This text is what the key event just before it produced. A program that already used that
 * event's text must not insert it again.
 */
static const WGUITextFlags WGUITextFlags_FromKey = 0x00000001;
/** The text was too long for one record: the next record of this type continues it. */
static const WGUITextFlags WGUITextFlags_Continues = 0x00000002;

typedef uint32_t WGUIClipboardFlags;
static const WGUIClipboardFlags WGUIClipboardFlags_None = 0x00000000;
/** This instance wrote the current content. */
static const WGUIClipboardFlags WGUIClipboardFlags_Owned = 0x00000001;
/** There is text. Not set when the host cannot tell without a request. */
static const WGUIClipboardFlags WGUIClipboardFlags_HasText = 0x00000002;
/** Reading will answer WGUIStatus_Pending until a request completes. */
static const WGUIClipboardFlags WGUIClipboardFlags_NeedsRequest = 0x00000004;

/** The embedder's own reactions to input. */
typedef uint32_t WGUIDefaultActions;
static const WGUIDefaultActions WGUIDefaultActions_None = 0x00000000;
/**
 * Keys pressed without Control, Alt or Super: scrolling with the space bar and the arrows,
 * moving focus with Tab.
 */
static const WGUIDefaultActions WGUIDefaultActions_Keys = 0x00000001;
/**
 * Key combinations the embedder lets a page take (save, print, find). Others (closing the tab)
 * cannot be prevented.
 */
static const WGUIDefaultActions WGUIDefaultActions_Shortcuts = 0x00000002;
/** Scrolling and zooming the page. */
static const WGUIDefaultActions WGUIDefaultActions_Wheel = 0x00000004;
static const WGUIDefaultActions WGUIDefaultActions_ContextMenu = 0x00000008;
/** Panning and zooming the page by touch. */
static const WGUIDefaultActions WGUIDefaultActions_TouchGestures = 0x00000010;
/** What a new window prevents. */
static const WGUIDefaultActions WGUIDefaultActions_Default = 0x0000001D;

typedef uint32_t WGUIDisplayFlags;
static const WGUIDisplayFlags WGUIDisplayFlags_None = 0x00000000;
static const WGUIDisplayFlags WGUIDisplayFlags_Primary = 0x00000001;

/** Kinds of input hardware. */
typedef uint32_t WGUIInputDevices;
static const WGUIInputDevices WGUIInputDevices_None = 0x00000000;
static const WGUIInputDevices WGUIInputDevices_Keyboard = 0x00000001;
static const WGUIInputDevices WGUIInputDevices_Mouse = 0x00000002;
static const WGUIInputDevices WGUIInputDevices_Touch = 0x00000004;
static const WGUIInputDevices WGUIInputDevices_Pen = 0x00000008;

// -- Keys -----------------------------------------------------------------

/**
 * What a key means on the user's layout: the KeyboardEvent `key` of the W3C UI Events
 * specification, as a number. The top byte is a tag (WGUI_KEY_TAG) and the rest its value
 * (WGUI_KEY_VALUE):
 *
 * WGUI_KEY_CHARACTER: the Unicode scalar value the key produces, so 'a' is 0x61. 0 is
 * WGUIKey_Unidentified.
 *
 * WGUI_KEY_NAMED: one of the WGUIKey_* constants below.
 *
 * WGUI_KEY_DEAD: a dead key; the value is the combining character it adds, or 0.
 *
 * WGUI_KEY_SEQUENCE: more than one scalar value; the value is the first and the event's
 * keyString has all.
 */
typedef uint32_t WGUIKey;
#define WGUI_KEY_TAG(key) ((key) & WGUI_KEY_TAG_MASK)
#define WGUI_KEY_VALUE(key) ((key) & WGUI_KEY_VALUE_MASK)

/** The named keys. (An enum rather than constants so that they work as `case` labels.) */
enum {
    WGUIKey_Unidentified = 0x00000000,
    WGUIKey_Backspace = 0x01000008,
    WGUIKey_Tab = 0x01000009,
    WGUIKey_Enter = 0x0100000D,
    WGUIKey_Escape = 0x0100001B,
    WGUIKey_Delete = 0x0100007F,
    WGUIKey_Accel = 0x01000101,
    WGUIKey_Alt = 0x01000102,
    WGUIKey_AltGraph = 0x01000103,
    WGUIKey_CapsLock = 0x01000104,
    WGUIKey_Control = 0x01000105,
    WGUIKey_Fn = 0x01000106,
    WGUIKey_FnLock = 0x01000107,
    WGUIKey_Hyper = 0x01000108,
    WGUIKey_Meta = 0x01000109,
    WGUIKey_NumLock = 0x0100010A,
    WGUIKey_ScrollLock = 0x0100010C,
    WGUIKey_Shift = 0x0100010D,
    WGUIKey_Super = 0x0100010E,
    WGUIKey_Symbol = 0x0100010F,
    WGUIKey_SymbolLock = 0x01000110,
    WGUIKey_ShiftLevel5 = 0x01000111,
    WGUIKey_ArrowDown = 0x01000301,
    WGUIKey_ArrowLeft = 0x01000302,
    WGUIKey_ArrowRight = 0x01000303,
    WGUIKey_ArrowUp = 0x01000304,
    WGUIKey_End = 0x01000305,
    WGUIKey_Home = 0x01000306,
    WGUIKey_PageDown = 0x01000307,
    WGUIKey_PageUp = 0x01000308,
    WGUIKey_Clear = 0x01000401,
    WGUIKey_Copy = 0x01000402,
    WGUIKey_CrSel = 0x01000403,
    WGUIKey_Cut = 0x01000404,
    WGUIKey_EraseEof = 0x01000405,
    WGUIKey_ExSel = 0x01000406,
    WGUIKey_Insert = 0x01000407,
    WGUIKey_Paste = 0x01000408,
    WGUIKey_Redo = 0x01000409,
    WGUIKey_Undo = 0x0100040A,
    WGUIKey_Accept = 0x01000501,
    WGUIKey_Again = 0x01000502,
    WGUIKey_Attn = 0x01000503,
    WGUIKey_Cancel = 0x01000504,
    WGUIKey_ContextMenu = 0x01000505,
    WGUIKey_Execute = 0x01000506,
    WGUIKey_Find = 0x01000507,
    WGUIKey_Help = 0x01000508,
    WGUIKey_Pause = 0x01000509,
    WGUIKey_Play = 0x0100050A,
    WGUIKey_Props = 0x0100050B,
    WGUIKey_Select = 0x0100050C,
    WGUIKey_ZoomIn = 0x0100050D,
    WGUIKey_ZoomOut = 0x0100050E,
    WGUIKey_BrightnessDown = 0x01000601,
    WGUIKey_BrightnessUp = 0x01000602,
    WGUIKey_Eject = 0x01000604,
    WGUIKey_LogOff = 0x01000605,
    WGUIKey_Power = 0x01000606,
    WGUIKey_PowerOff = 0x01000607,
    WGUIKey_PrintScreen = 0x01000608,
    WGUIKey_Hibernate = 0x01000609,
    WGUIKey_Standby = 0x0100060A,
    WGUIKey_WakeUp = 0x0100060B,
    WGUIKey_AllCandidates = 0x01000701,
    WGUIKey_Alphanumeric = 0x01000702,
    WGUIKey_CodeInput = 0x01000703,
    WGUIKey_Compose = 0x01000704,
    WGUIKey_Convert = 0x01000705,
    WGUIKey_FinalMode = 0x01000706,
    WGUIKey_GroupFirst = 0x01000707,
    WGUIKey_GroupLast = 0x01000708,
    WGUIKey_GroupNext = 0x01000709,
    WGUIKey_GroupPrevious = 0x0100070A,
    WGUIKey_ModeChange = 0x0100070B,
    WGUIKey_NextCandidate = 0x0100070C,
    WGUIKey_NonConvert = 0x0100070D,
    WGUIKey_PreviousCandidate = 0x0100070E,
    WGUIKey_Process = 0x0100070F,
    WGUIKey_SingleCandidate = 0x01000710,
    WGUIKey_HangulMode = 0x01000711,
    WGUIKey_HanjaMode = 0x01000712,
    WGUIKey_JunjaMode = 0x01000713,
    WGUIKey_Eisu = 0x01000714,
    WGUIKey_Hankaku = 0x01000715,
    WGUIKey_Hiragana = 0x01000716,
    WGUIKey_HiraganaKatakana = 0x01000717,
    WGUIKey_KanaMode = 0x01000718,
    WGUIKey_KanjiMode = 0x01000719,
    WGUIKey_Katakana = 0x0100071A,
    WGUIKey_Romaji = 0x0100071B,
    WGUIKey_Zenkaku = 0x0100071C,
    WGUIKey_ZenkakuHankaku = 0x0100071D,
    WGUIKey_F1 = 0x01000801,
    WGUIKey_F2 = 0x01000802,
    WGUIKey_F3 = 0x01000803,
    WGUIKey_F4 = 0x01000804,
    WGUIKey_F5 = 0x01000805,
    WGUIKey_F6 = 0x01000806,
    WGUIKey_F7 = 0x01000807,
    WGUIKey_F8 = 0x01000808,
    WGUIKey_F9 = 0x01000809,
    WGUIKey_F10 = 0x0100080A,
    WGUIKey_F11 = 0x0100080B,
    WGUIKey_F12 = 0x0100080C,
    WGUIKey_F13 = 0x0100080D,
    WGUIKey_F14 = 0x0100080E,
    WGUIKey_F15 = 0x0100080F,
    WGUIKey_F16 = 0x01000810,
    WGUIKey_F17 = 0x01000811,
    WGUIKey_F18 = 0x01000812,
    WGUIKey_F19 = 0x01000813,
    WGUIKey_F20 = 0x01000814,
    WGUIKey_F21 = 0x01000815,
    WGUIKey_F22 = 0x01000816,
    WGUIKey_F23 = 0x01000817,
    WGUIKey_F24 = 0x01000818,
    WGUIKey_Soft1 = 0x01000901,
    WGUIKey_Soft2 = 0x01000902,
    WGUIKey_Soft3 = 0x01000903,
    WGUIKey_Soft4 = 0x01000904,
    WGUIKey_Soft5 = 0x01000905,
    WGUIKey_Soft6 = 0x01000906,
    WGUIKey_Soft7 = 0x01000907,
    WGUIKey_Soft8 = 0x01000908,
    WGUIKey_ChannelDown = 0x01000D0A,
    WGUIKey_ChannelUp = 0x01000D0B,
    WGUIKey_Close = 0x01000A01,
    WGUIKey_MailForward = 0x01000A02,
    WGUIKey_MailReply = 0x01000A03,
    WGUIKey_MailSend = 0x01000A04,
    WGUIKey_MediaClose = 0x01000D5B,
    WGUIKey_MediaFastForward = 0x01000D2C,
    WGUIKey_MediaPause = 0x01000D2E,
    WGUIKey_MediaPlay = 0x01000D2F,
    WGUIKey_MediaPlayPause = 0x01000A05,
    WGUIKey_MediaRecord = 0x01000D30,
    WGUIKey_MediaRewind = 0x01000D31,
    WGUIKey_MediaStop = 0x01000A07,
    WGUIKey_MediaTrackNext = 0x01000A08,
    WGUIKey_MediaTrackPrevious = 0x01000A09,
    WGUIKey_New = 0x01000A0A,
    WGUIKey_Open = 0x01000A0B,
    WGUIKey_Print = 0x01000A0C,
    WGUIKey_Save = 0x01000A0D,
    WGUIKey_SpellCheck = 0x01000A0E,
    WGUIKey_Key11 = 0x01001201,
    WGUIKey_Key12 = 0x01001202,
    WGUIKey_AudioBalanceLeft = 0x01000D01,
    WGUIKey_AudioBalanceRight = 0x01000D02,
    WGUIKey_AudioBassBoostDown = 0x01000D03,
    WGUIKey_AudioBassBoostToggle = 0x01000E02,
    WGUIKey_AudioBassBoostUp = 0x01000D04,
    WGUIKey_AudioFaderFront = 0x01000D05,
    WGUIKey_AudioFaderRear = 0x01000D06,
    WGUIKey_AudioSurroundModeNext = 0x01000D07,
    WGUIKey_AudioTrebleDown = 0x01000E04,
    WGUIKey_AudioTrebleUp = 0x01000E05,
    WGUIKey_AudioVolumeDown = 0x01000A0F,
    WGUIKey_AudioVolumeUp = 0x01000A10,
    WGUIKey_AudioVolumeMute = 0x01000A11,
    WGUIKey_MicrophoneToggle = 0x01000E06,
    WGUIKey_MicrophoneVolumeDown = 0x01000E07,
    WGUIKey_MicrophoneVolumeUp = 0x01000E08,
    WGUIKey_MicrophoneVolumeMute = 0x01000E09,
    WGUIKey_SpeechCorrectionList = 0x01000F01,
    WGUIKey_SpeechInputToggle = 0x01000F02,
    WGUIKey_LaunchApplication1 = 0x01000B06,
    WGUIKey_LaunchApplication2 = 0x01000B01,
    WGUIKey_LaunchCalendar = 0x01000B02,
    WGUIKey_LaunchContacts = 0x01000B0C,
    WGUIKey_LaunchMail = 0x01000B03,
    WGUIKey_LaunchMediaPlayer = 0x01000B04,
    WGUIKey_LaunchMusicPlayer = 0x01000B05,
    WGUIKey_LaunchPhone = 0x01000B0D,
    WGUIKey_LaunchScreenSaver = 0x01000B07,
    WGUIKey_LaunchSpreadsheet = 0x01000B08,
    WGUIKey_LaunchWebBrowser = 0x01000B09,
    WGUIKey_LaunchWebCam = 0x01000B0A,
    WGUIKey_LaunchWordProcessor = 0x01000B0B,
    WGUIKey_LaunchAssistant = 0x01000B0E,
    WGUIKey_LaunchControlPanel = 0x01000B0F,
    WGUIKey_BrowserBack = 0x01000C01,
    WGUIKey_BrowserFavorites = 0x01000C02,
    WGUIKey_BrowserForward = 0x01000C03,
    WGUIKey_BrowserHome = 0x01000C04,
    WGUIKey_BrowserRefresh = 0x01000C05,
    WGUIKey_BrowserSearch = 0x01000C06,
    WGUIKey_BrowserStop = 0x01000C07,
    WGUIKey_AppSwitch = 0x01001001,
    WGUIKey_Call = 0x01001002,
    WGUIKey_Camera = 0x01000603,
    WGUIKey_CameraFocus = 0x01001003,
    WGUIKey_EndCall = 0x01001004,
    WGUIKey_GoBack = 0x01001005,
    WGUIKey_GoHome = 0x01001006,
    WGUIKey_HeadsetHook = 0x01001007,
    WGUIKey_LastNumberRedial = 0x01001008,
    WGUIKey_Notification = 0x01001009,
    WGUIKey_MannerMode = 0x0100100A,
    WGUIKey_VoiceDial = 0x0100100B,
    WGUIKey_TV = 0x01000D49,
    WGUIKey_TV3DMode = 0x01001101,
    WGUIKey_TVAntennaCable = 0x01001102,
    WGUIKey_TVAudioDescription = 0x01001103,
    WGUIKey_TVAudioDescriptionMixDown = 0x01001104,
    WGUIKey_TVAudioDescriptionMixUp = 0x01001105,
    WGUIKey_TVContentsMenu = 0x01001106,
    WGUIKey_TVDataService = 0x01001107,
    WGUIKey_TVInput = 0x01000D4A,
    WGUIKey_TVInputComponent1 = 0x01001108,
    WGUIKey_TVInputComponent2 = 0x01001109,
    WGUIKey_TVInputComposite1 = 0x0100110A,
    WGUIKey_TVInputComposite2 = 0x0100110B,
    WGUIKey_TVInputHDMI1 = 0x0100110C,
    WGUIKey_TVInputHDMI2 = 0x0100110D,
    WGUIKey_TVInputHDMI3 = 0x0100110E,
    WGUIKey_TVInputHDMI4 = 0x0100110F,
    WGUIKey_TVInputVGA1 = 0x01001110,
    WGUIKey_TVMediaContext = 0x01001111,
    WGUIKey_TVNetwork = 0x01001112,
    WGUIKey_TVNumberEntry = 0x01001113,
    WGUIKey_TVPower = 0x01000D4B,
    WGUIKey_TVRadioService = 0x01001114,
    WGUIKey_TVSatellite = 0x01001115,
    WGUIKey_TVSatelliteBS = 0x01001116,
    WGUIKey_TVSatelliteCS = 0x01001117,
    WGUIKey_TVSatelliteToggle = 0x01001118,
    WGUIKey_TVTerrestrialAnalog = 0x01001119,
    WGUIKey_TVTerrestrialDigital = 0x0100111A,
    WGUIKey_TVTimer = 0x0100111B,
    WGUIKey_AVRInput = 0x01000D08,
    WGUIKey_AVRPower = 0x01000D09,
    WGUIKey_ColorF0Red = 0x01000D0C,
    WGUIKey_ColorF1Green = 0x01000D0D,
    WGUIKey_ColorF2Yellow = 0x01000D0E,
    WGUIKey_ColorF3Blue = 0x01000D0F,
    WGUIKey_ColorF4Grey = 0x01000D10,
    WGUIKey_ColorF5Brown = 0x01000D11,
    WGUIKey_ClosedCaptionToggle = 0x01000D12,
    WGUIKey_Dimmer = 0x01000D13,
    WGUIKey_DisplaySwap = 0x01000D14,
    WGUIKey_DVR = 0x01000D4F,
    WGUIKey_Exit = 0x01000D15,
    WGUIKey_FavoriteClear0 = 0x01000D16,
    WGUIKey_FavoriteClear1 = 0x01000D17,
    WGUIKey_FavoriteClear2 = 0x01000D18,
    WGUIKey_FavoriteClear3 = 0x01000D19,
    WGUIKey_FavoriteRecall0 = 0x01000D1A,
    WGUIKey_FavoriteRecall1 = 0x01000D1B,
    WGUIKey_FavoriteRecall2 = 0x01000D1C,
    WGUIKey_FavoriteRecall3 = 0x01000D1D,
    WGUIKey_FavoriteStore0 = 0x01000D1E,
    WGUIKey_FavoriteStore1 = 0x01000D1F,
    WGUIKey_FavoriteStore2 = 0x01000D20,
    WGUIKey_FavoriteStore3 = 0x01000D21,
    WGUIKey_Guide = 0x01000D22,
    WGUIKey_GuideNextDay = 0x01000D23,
    WGUIKey_GuidePreviousDay = 0x01000D24,
    WGUIKey_Info = 0x01000D25,
    WGUIKey_InstantReplay = 0x01000D26,
    WGUIKey_Link = 0x01000D27,
    WGUIKey_ListProgram = 0x01000D28,
    WGUIKey_LiveContent = 0x01000D29,
    WGUIKey_Lock = 0x01000D2A,
    WGUIKey_MediaApps = 0x01000D2B,
    WGUIKey_MediaAudioTrack = 0x01000D50,
    WGUIKey_MediaLast = 0x01000D2D,
    WGUIKey_MediaSkipBackward = 0x01000D51,
    WGUIKey_MediaSkipForward = 0x01000D52,
    WGUIKey_MediaSkip = 0x01000D32,
    WGUIKey_MediaStepBackward = 0x01000D53,
    WGUIKey_MediaStepForward = 0x01000D54,
    WGUIKey_MediaTopMenu = 0x01000D55,
    WGUIKey_NavigateIn = 0x01000D56,
    WGUIKey_NavigateNext = 0x01000D57,
    WGUIKey_NavigateOut = 0x01000D58,
    WGUIKey_NavigatePrevious = 0x01000D59,
    WGUIKey_NextFavoriteChannel = 0x01000D33,
    WGUIKey_NextUserProfile = 0x01000D34,
    WGUIKey_OnDemand = 0x01000D35,
    WGUIKey_Pairing = 0x01000D5A,
    WGUIKey_PinPDown = 0x01000D36,
    WGUIKey_PinPMove = 0x01000D37,
    WGUIKey_PinPToggle = 0x01000D38,
    WGUIKey_PinPUp = 0x01000D39,
    WGUIKey_PlaySpeedDown = 0x01000D3A,
    WGUIKey_PlaySpeedReset = 0x01000D3B,
    WGUIKey_PlaySpeedUp = 0x01000D3C,
    WGUIKey_RandomToggle = 0x01000D3D,
    WGUIKey_RcLowBattery = 0x01000D3E,
    WGUIKey_RecordSpeedNext = 0x01000D3F,
    WGUIKey_RfBypass = 0x01000D40,
    WGUIKey_ScanChannelsToggle = 0x01000D41,
    WGUIKey_ScreenModeNext = 0x01000D42,
    WGUIKey_Settings = 0x01000D43,
    WGUIKey_SplitScreenToggle = 0x01000D44,
    WGUIKey_STBInput = 0x01000D45,
    WGUIKey_STBPower = 0x01000D46,
    WGUIKey_Subtitle = 0x01000D47,
    WGUIKey_Teletext = 0x01000D48,
    WGUIKey_VideoModeNext = 0x01000D4C,
    WGUIKey_Wink = 0x01000D4D,
    WGUIKey_ZoomToggle = 0x01000D4E,
    WGUIKey_F25 = 0x01004019,
    WGUIKey_F26 = 0x0100401A,
    WGUIKey_F27 = 0x0100401B,
    WGUIKey_F28 = 0x0100401C,
    WGUIKey_F29 = 0x0100401D,
    WGUIKey_F30 = 0x0100401E,
    WGUIKey_F31 = 0x0100401F,
    WGUIKey_F32 = 0x01004020,
    WGUIKey_F33 = 0x01004021,
    WGUIKey_F34 = 0x01004022,
    WGUIKey_F35 = 0x01004023
};

// -- Structures -----------------------------------------------------------

/**
 * The start of a struct that extends another through its nextInChain list. Hosts skip structs
 * they do not know, unless the sType has WGUI_STYPE_MUST_UNDERSTAND set.
 */
typedef struct WGUIChainedStruct {
    struct WGUIChainedStruct* next;
    WGUISType sType;
} WGUIChainedStruct;

/** A rectangle in a window, in physical pixels from the content area's top-left corner. */
typedef struct WGUIRect {
    int32_t x;
    int32_t y;
    uint32_t width;
    uint32_t height;
} WGUIRect;

#define WGUI_RECT_INIT WGUI_MAKE_INIT_STRUCT(WGUIRect, { \
    /*.x=*/0 WGUI_COMMA \
    /*.y=*/0 WGUI_COMMA \
    /*.width=*/0 WGUI_COMMA \
    /*.height=*/0 \
})

typedef struct WGUIInstanceDescriptor {
    WGUIChainedStruct* nextInChain;
    /** The version of the header the program was built with. Leave it as the INIT macro sets it. */
    uint32_t abiVersion;
    /** The classes of events to queue. See wguiInstanceSetEventMask. */
    WGUIEventClass eventMask;
    size_t requiredFeatureCount;
    /** Features the program cannot do without. */
    const WGUIFeatureName* requiredFeatures;
    /**
     * A stable name for the program, such as "org.example.editor". Window systems use it to
     * group windows and to find the program's icon and name.
     */
    WGUIStringView applicationId;
} WGUIInstanceDescriptor;

#define WGUI_INSTANCE_DESCRIPTOR_INIT WGUI_MAKE_INIT_STRUCT(WGUIInstanceDescriptor, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.abiVersion=*/WGUI_ABI_VERSION WGUI_COMMA \
    /*.eventMask=*/0x00000000000009FE /* Default */ WGUI_COMMA \
    /*.requiredFeatureCount=*/0 WGUI_COMMA \
    /*.requiredFeatures=*/NULL WGUI_COMMA \
    /*.applicationId=*/WGUI_STRING_VIEW_INIT \
})

typedef struct WGUIInstanceInfo {
    WGUIChainedStruct* nextInChain;
    /** The newest version the host implements. */
    uint32_t abiVersion;
    WGUIHostKind hostKind;
    /** The modifier this platform's shortcuts use: Control, or Super on a Mac. */
    WGUIModifiers shortcutModifier;
    /**
     * The input hardware the host knows of. A keyboard missing here is the reason to show an
     * on-screen one.
     */
    WGUIInputDevices inputDevices;
    WGUITheme systemTheme;
    /** The largest width or height a custom cursor may have, in pixels. 0 if unknown. */
    uint32_t maxCursorSize;
} WGUIInstanceInfo;

#define WGUI_INSTANCE_INFO_INIT WGUI_MAKE_INIT_STRUCT(WGUIInstanceInfo, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.abiVersion=*/0 WGUI_COMMA \
    /*.hostKind=*/WGUIHostKind_Unknown WGUI_COMMA \
    /*.shortcutModifier=*/0x00000000 WGUI_COMMA \
    /*.inputDevices=*/0x00000000 WGUI_COMMA \
    /*.systemTheme=*/WGUITheme_Unknown WGUI_COMMA \
    /*.maxCursorSize=*/0 \
})

typedef struct WGUIDisplayInfo {
    WGUIChainedStruct* nextInChain;
    /** The display's top-left corner on the desktop. */
    int32_t x;
    int32_t y;
    uint32_t width;
    uint32_t height;
    /** The part of the display windows can use: without docks, panels and menu bars. */
    int32_t workX;
    int32_t workY;
    uint32_t workWidth;
    uint32_t workHeight;
    /** Physical pixels per logical unit. */
    double scaleFactor;
    /** In thousandths of a hertz. 0 if unknown. */
    uint32_t refreshRate;
    WGUIDisplayFlags flags;
} WGUIDisplayInfo;

#define WGUI_DISPLAY_INFO_INIT WGUI_MAKE_INIT_STRUCT(WGUIDisplayInfo, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.x=*/0 WGUI_COMMA \
    /*.y=*/0 WGUI_COMMA \
    /*.width=*/0 WGUI_COMMA \
    /*.height=*/0 WGUI_COMMA \
    /*.workX=*/0 WGUI_COMMA \
    /*.workY=*/0 WGUI_COMMA \
    /*.workWidth=*/0 WGUI_COMMA \
    /*.workHeight=*/0 WGUI_COMMA \
    /*.scaleFactor=*/0.0 WGUI_COMMA \
    /*.refreshRate=*/0 WGUI_COMMA \
    /*.flags=*/0x00000000 \
})

typedef struct WGUIWindowDescriptor {
    WGUIChainedStruct* nextInChain;
    WGUIStringView title;
    /**
     * The name of a target the embedder provides (a canvas, a view) for the window to adopt.
     * Empty is the embedder's default target. Naming a target does not need
     * WGUIFeatureName_TopLevelWindows; a target already adopted answers WGUIStatus_Busy.
     */
    WGUIStringView target;
    /** The requestable flags to start with. */
    WGUIWindowFlags flags;
    WGUIWindowOptions options;
    /**
     * The size of the content area. 0 lets the host choose. An adopted target keeps its own
     * size.
     */
    uint32_t width;
    uint32_t height;
    /** Limits, as in wguiWindowSetSizeLimits. */
    uint32_t minWidth;
    uint32_t minHeight;
    uint32_t maxWidth;
    uint32_t maxHeight;
    /** Used with WGUIWindowOptions_Positioned. */
    int32_t x;
    int32_t y;
    /** The display to open on. 0 lets the host choose. */
    WGUIDisplay display;
} WGUIWindowDescriptor;

#define WGUI_WINDOW_DESCRIPTOR_INIT WGUI_MAKE_INIT_STRUCT(WGUIWindowDescriptor, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.title=*/WGUI_STRING_VIEW_INIT WGUI_COMMA \
    /*.target=*/WGUI_STRING_VIEW_INIT WGUI_COMMA \
    /*.flags=*/0x0000000000000007 /* Visible | Resizable | Decorated */ WGUI_COMMA \
    /*.options=*/0x00000000 WGUI_COMMA \
    /*.width=*/0 WGUI_COMMA \
    /*.height=*/0 WGUI_COMMA \
    /*.minWidth=*/0 WGUI_COMMA \
    /*.minHeight=*/0 WGUI_COMMA \
    /*.maxWidth=*/0 WGUI_COMMA \
    /*.maxHeight=*/0 WGUI_COMMA \
    /*.x=*/0 WGUI_COMMA \
    /*.y=*/0 WGUI_COMMA \
    /*.display=*/0 \
})

typedef struct WGUIWindowState {
    WGUIChainedStruct* nextInChain;
    /** The size of the content area: what a surface on the window should be configured with. */
    uint32_t width;
    uint32_t height;
    /** Physical pixels per logical unit, for sizing text and controls. */
    double scaleFactor;
    /** The content area's top-left corner on the desktop, or WGUI_POSITION_UNDEFINED. */
    int32_t x;
    int32_t y;
    /** How far the window's borders and title bar reach beyond the content area. */
    uint32_t frameLeft;
    uint32_t frameTop;
    uint32_t frameRight;
    uint32_t frameBottom;
    /**
     * How much of the content area's edges may be covered by notches, rounded corners or system
     * bars.
     */
    uint32_t safeLeft;
    uint32_t safeTop;
    uint32_t safeRight;
    uint32_t safeBottom;
    WGUIWindowFlags flags;
    /** The display most of the window is on, or 0. */
    WGUIDisplay display;
    WGUIFullscreenMode fullscreen;
    /** The grab in effect now, which may be less than what was asked for. */
    WGUICursorGrab cursorGrab;
    WGUITheme theme;
    /** Goes up whenever anything in this struct changes. */
    uint32_t serial;
} WGUIWindowState;

#define WGUI_WINDOW_STATE_INIT WGUI_MAKE_INIT_STRUCT(WGUIWindowState, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.width=*/0 WGUI_COMMA \
    /*.height=*/0 WGUI_COMMA \
    /*.scaleFactor=*/0.0 WGUI_COMMA \
    /*.x=*/0 WGUI_COMMA \
    /*.y=*/0 WGUI_COMMA \
    /*.frameLeft=*/0 WGUI_COMMA \
    /*.frameTop=*/0 WGUI_COMMA \
    /*.frameRight=*/0 WGUI_COMMA \
    /*.frameBottom=*/0 WGUI_COMMA \
    /*.safeLeft=*/0 WGUI_COMMA \
    /*.safeTop=*/0 WGUI_COMMA \
    /*.safeRight=*/0 WGUI_COMMA \
    /*.safeBottom=*/0 WGUI_COMMA \
    /*.flags=*/0x0000000000000000 WGUI_COMMA \
    /*.display=*/0 WGUI_COMMA \
    /*.fullscreen=*/WGUIFullscreenMode_None WGUI_COMMA \
    /*.cursorGrab=*/WGUICursorGrab_None WGUI_COMMA \
    /*.theme=*/WGUITheme_Unknown WGUI_COMMA \
    /*.serial=*/0 \
})

typedef struct WGUIFullscreenOptions {
    WGUIChainedStruct* nextInChain;
    WGUIFullscreenMode mode;
    /** The display to cover. 0 is the one the window is on. */
    WGUIDisplay display;
    WGUIFullscreenFlags flags;
} WGUIFullscreenOptions;

#define WGUI_FULLSCREEN_OPTIONS_INIT WGUI_MAKE_INIT_STRUCT(WGUIFullscreenOptions, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.mode=*/WGUIFullscreenMode_Borderless WGUI_COMMA \
    /*.display=*/0 WGUI_COMMA \
    /*.flags=*/0x00000000 \
})

typedef struct WGUICursorDescriptor {
    WGUIChainedStruct* nextInChain;
    /** The image's size in pixels. */
    uint32_t width;
    uint32_t height;
    /** The pixel that points. */
    uint32_t hotspotX;
    uint32_t hotspotY;
    /**
     * How many image pixels make one logical unit: 2 for an image drawn for a display of scale
     * factor 2.
     */
    double scaleFactor;
    /** RGBA, 8 bits each, alpha not premultiplied, rows from the top, no padding. */
    const void* pixels;
    /** width * height * 4. */
    size_t pixelsSize;
} WGUICursorDescriptor;

#define WGUI_CURSOR_DESCRIPTOR_INIT WGUI_MAKE_INIT_STRUCT(WGUICursorDescriptor, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.width=*/0 WGUI_COMMA \
    /*.height=*/0 WGUI_COMMA \
    /*.hotspotX=*/0 WGUI_COMMA \
    /*.hotspotY=*/0 WGUI_COMMA \
    /*.scaleFactor=*/1.0 WGUI_COMMA \
    /*.pixels=*/NULL WGUI_COMMA \
    /*.pixelsSize=*/0 \
})

/** A frame for wguiWindowPresentPixels: rows of pixels from the top, each row from the left. */
typedef struct WGUIPixelFrame {
    WGUIChainedStruct* nextInChain;
    /** The frame's size in pixels. */
    uint32_t width;
    uint32_t height;
    /** Bytes from the start of one row to the start of the next. 0 means width * 4: no padding. */
    uint32_t stride;
    WGUIPixelFormat format;
    WGUIPixelAlpha alpha;
    const void* pixels;
    /** How much of `pixels` may be read: at least stride * (height - 1) + width * 4. */
    size_t pixelsSize;
} WGUIPixelFrame;

#define WGUI_PIXEL_FRAME_INIT WGUI_MAKE_INIT_STRUCT(WGUIPixelFrame, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.width=*/0 WGUI_COMMA \
    /*.height=*/0 WGUI_COMMA \
    /*.stride=*/0 WGUI_COMMA \
    /*.format=*/WGUIPixelFormat_Bgra8 WGUI_COMMA \
    /*.alpha=*/WGUIPixelAlpha_Opaque WGUI_COMMA \
    /*.pixels=*/NULL WGUI_COMMA \
    /*.pixelsSize=*/0 \
})

typedef struct WGUITextInputDescriptor {
    WGUIChainedStruct* nextInChain;
    WGUITextInputPurpose purpose;
    WGUITextInputHints hints;
    WGUIScreenKeyboardPolicy screenKeyboard;
    /** Where the caret is, so the input method can put its candidate window next to it. */
    WGUIRect cursorArea;
    /**
     * The whole text field, so an on-screen keyboard can avoid covering it. Zero size if
     * unknown.
     */
    WGUIRect inputArea;
} WGUITextInputDescriptor;

#define WGUI_TEXT_INPUT_DESCRIPTOR_INIT WGUI_MAKE_INIT_STRUCT(WGUITextInputDescriptor, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.purpose=*/WGUITextInputPurpose_Normal WGUI_COMMA \
    /*.hints=*/0x00000000 WGUI_COMMA \
    /*.screenKeyboard=*/WGUIScreenKeyboardPolicy_Auto WGUI_COMMA \
    /*.cursorArea=*/WGUI_RECT_INIT WGUI_COMMA \
    /*.inputArea=*/WGUI_RECT_INIT \
})

typedef struct WGUIClipboardInfo {
    WGUIChainedStruct* nextInChain;
    /** Goes up whenever the content changes, as far as the host notices. */
    uint32_t sequence;
    WGUIClipboardFlags flags;
} WGUIClipboardInfo;

#define WGUI_CLIPBOARD_INFO_INIT WGUI_MAKE_INIT_STRUCT(WGUIClipboardInfo, { \
    /*.nextInChain=*/NULL WGUI_COMMA \
    /*.sequence=*/0 WGUI_COMMA \
    /*.flags=*/0x00000000 \
})

/** One representation of what is being copied. */
typedef struct WGUIClipboardItem {
    /** "text/plain" for UTF-8 text. */
    WGUIStringView mimeType;
    const void* data;
    size_t size;
} WGUIClipboardItem;

#define WGUI_CLIPBOARD_ITEM_INIT WGUI_MAKE_INIT_STRUCT(WGUIClipboardItem, { \
    /*.mimeType=*/WGUI_STRING_VIEW_INIT WGUI_COMMA \
    /*.data=*/NULL WGUI_COMMA \
    /*.size=*/0 \
})

// -- Event records --------------------------------------------------------

/**
 * What every event record starts with. Records are little-endian, 8-byte aligned, and say how
 * long they are: a record a program does not know, or one longer than it expects, is stepped
 * over by its size.
 */
typedef struct WGUIEventHeader {
    /**
     * The whole record in bytes, strings and padding included; a multiple of 8. The next record
     * starts this far on.
     */
    uint32_t size;
    WGUIEventType type;
    WGUIEventFlags flags;
    /** The window the event is for, or 0. */
    WGUIWindow window;
    /**
     * When it happened, in nanoseconds on the clock of wguiInstanceGetTime. Never decreases
     * from one record to the next.
     */
    uint64_t timestamp;
    /** Which piece of hardware, where the host can tell them apart; 0 otherwise. */
    uint32_t device;
    /** Counts the records this instance has been given. */
    uint32_t sequence;
} WGUIEventHeader;

/**
 * A string inside an event record: `length` bytes of UTF-8 starting `offset` bytes from the
 * start of the record. An offset of 0 means there is no string. See wguiEventGetString.
 */
typedef struct WGUIEventString {
    uint32_t offset;
    uint32_t length;
} WGUIEventString;

/**
 * The queue overflowed and records were dropped. What follows makes the program's view right
 * again: releases for keys and buttons it believes held, and each window's current size and
 * flags. Dropped text is gone.
 */
typedef struct WGUIEventsLostEvent {
    WGUIEventHeader header;
    /** How many records were dropped. */
    uint32_t count;
    uint32_t reserved;
    /** The classes they belonged to. */
    WGUIEventClass classes;
} WGUIEventsLostEvent;

/**
 * A request made with a tag is over. Every accepted request gets exactly one, also when its
 * window is destroyed first.
 */
typedef struct WGUIRequestCompletedEvent {
    WGUIEventHeader header;
    /** The tag the program passed. */
    uint64_t tag;
    WGUIRequestKind kind;
    WGUIStatus status;
} WGUIRequestCompletedEvent;

typedef struct WGUIThemeEvent {
    WGUIEventHeader header;
    WGUITheme theme;
    uint32_t reserved;
} WGUIThemeEvent;

/**
 * The window's content area has a new size or scale factor. A surface on it should be
 * configured again with this size.
 */
typedef struct WGUIWindowResizedEvent {
    WGUIEventHeader header;
    uint32_t width;
    uint32_t height;
    double scaleFactor;
    WGUIResizeFlags changed;
    uint32_t reserved;
} WGUIWindowResizedEvent;

typedef struct WGUIWindowMovedEvent {
    WGUIEventHeader header;
    int32_t x;
    int32_t y;
} WGUIWindowMovedEvent;

typedef struct WGUIWindowFlagsChangedEvent {
    WGUIEventHeader header;
    /** All of the window's flags now. */
    WGUIWindowFlags flags;
    /** The ones that differ from before. */
    WGUIWindowFlags changed;
} WGUIWindowFlagsChangedEvent;

typedef struct WGUIWindowDisplayChangedEvent {
    WGUIEventHeader header;
    WGUIDisplay display;
    uint32_t reserved;
} WGUIWindowDisplayChangedEvent;

typedef struct WGUIWindowCursorGrabChangedEvent {
    WGUIEventHeader header;
    /** The grab in effect now. */
    WGUICursorGrab grab;
    WGUICursorGrabReason reason;
} WGUIWindowCursorGrabChangedEvent;

/**
 * A key went down or up.
 *
 * Per window, downs and ups pair up: no release arrives for a press the window did not get. A
 * held key repeats as further downs flagged Repeat. Before a window loses focus it gets a
 * synthetic release for every key still down.
 *
 * `text` is what the press types through the keyboard layout, with or without text input on.
 * While text input is on, the same text also arrives as a WGUIEventType_TextCommit flagged
 * FromKey.
 */
typedef struct WGUIKeyEvent {
    WGUIEventHeader header;
    /** Which key, wherever the layout puts its letters. */
    WGUIPhysicalKey physicalKey;
    /** The platform's own code for the key, for keys physicalKey cannot name. 0 if unknown. */
    uint32_t nativeScancode;
    /** What the key means with the modifiers held, Control aside. */
    WGUIKey key;
    /** What it means with no modifier held: the layout's base layer. 0 if unknown. */
    WGUIKey keyUnmodified;
    /** The modifiers after this event. */
    WGUIModifiers modifiers;
    WGUIKeyFlags keyFlags;
    WGUIKeyLocation location;
    uint32_t reserved;
    /** `key` as text when it is a character, a dead key or a sequence. */
    WGUIEventString keyString;
    /** The text this press types. Absent for releases and for keys that type nothing. */
    WGUIEventString text;
    /** The same with Control applied too, as terminals want it (Control+C is U+0003). */
    WGUIEventString textWithAllModifiers;
} WGUIKeyEvent;

/**
 * The modifiers changed. Follows the key event that caused it, and focus gained when some are
 * already held.
 */
typedef struct WGUIModifiersChangedEvent {
    WGUIEventHeader header;
    WGUIModifiers modifiers;
    uint32_t reserved;
} WGUIModifiersChangedEvent;

typedef struct WGUITextInputStateEvent {
    WGUIEventHeader header;
    WGUITextInputStateFlags stateFlags;
    uint32_t reserved;
    /** The part of the window an on-screen keyboard covers. Zero size if none. */
    WGUIRect keyboardArea;
} WGUITextInputStateEvent;

/**
 * The text being composed by an input method: it replaces the composition shown so far, and
 * empty text ends it. Draw it at the caret, marked as unfinished; it is not part of the
 * document.
 */
typedef struct WGUITextCompositionEvent {
    WGUIEventHeader header;
    /**
     * The input method's cursor or selection inside the text, as byte offsets, or
     * WGUI_NO_TEXT_CURSOR.
     */
    uint32_t selectionStart;
    uint32_t selectionEnd;
    WGUITextFlags textFlags;
    uint32_t reserved;
    WGUIEventString text;
} WGUITextCompositionEvent;

/**
 * Text to insert at the caret. Ends the composition, if there is one. While text input is on,
 * every insertion arrives this way, typed keys included.
 */
typedef struct WGUITextCommitEvent {
    WGUIEventHeader header;
    WGUITextFlags textFlags;
    uint32_t reserved;
    WGUIEventString text;
} WGUITextCommitEvent;

/**
 * A mouse cursor, a finger or a pen did something over a window.
 *
 * Every press and every release is its own Down or Up. From a Down until the pointer's last
 * button is up, its events go to that window even when it moves outside. Cancel means all of
 * that pointer's buttons are up and the gesture should be undone.
 */
typedef struct WGUIPointerEvent {
    WGUIEventHeader header;
    uint32_t pointerId;
    WGUIPointerKind pointerKind;
    WGUIPointerFlags pointerFlags;
    /** The button that went down or up. */
    WGUIPointerButton button;
    /** The buttons held after this event. */
    WGUIPointerButtons buttons;
    WGUIModifiers modifiers;
    /** Position in the window. */
    double x;
    double y;
    /**
     * Movement since this pointer's previous record. With the cursor locked this is all that
     * changes.
     */
    double deltaX;
    double deltaY;
    /** 0 to 1. Without WGUIPointerFlags_HasPressure: 0.5 in contact, else 0. */
    float pressure;
    /** A pen's barrel pressure, -1 to 1. */
    float tangentialPressure;
    /** Degrees from upright, -90 to 90. */
    float tiltX;
    float tiltY;
    /** Degrees of rotation about the pen's axis, 0 to 360. */
    float twist;
    /** The size of the contact, in physical pixels. 0 if unknown. */
    float contactWidth;
    float contactHeight;
    WGUIPointerTool tool;
    /** For a Down or Up: 2 for a double click, as the system counts them. 0 if unknown. */
    uint32_t clickCount;
    uint32_t reserved;
} WGUIPointerEvent;

/**
 * A wheel turned or a touchpad scrolled. Positive deltaY scrolls the content up, showing what
 * is below; positive deltaX shows what is to the right.
 */
typedef struct WGUIWheelEvent {
    WGUIEventHeader header;
    WGUIWheelUnit unit;
    WGUIWheelPhase phase;
    WGUIWheelFlags wheelFlags;
    WGUIModifiers modifiers;
    double deltaX;
    double deltaY;
    /** Where the cursor is. */
    double x;
    double y;
} WGUIWheelEvent;

/** A mouse moved, as the device reports it: no acceleration, no window. */
typedef struct WGUIRawMotionEvent {
    WGUIEventHeader header;
    double deltaX;
    double deltaY;
} WGUIRawMotionEvent;

typedef struct WGUIRawButtonEvent {
    WGUIEventHeader header;
    WGUIPointerButton button;
    uint32_t pressed;
} WGUIRawButtonEvent;

typedef struct WGUIRawWheelEvent {
    WGUIEventHeader header;
    WGUIWheelUnit unit;
    uint32_t reserved;
    double deltaX;
    double deltaY;
} WGUIRawWheelEvent;

typedef struct WGUIRawKeyEvent {
    WGUIEventHeader header;
    WGUIPhysicalKey physicalKey;
    uint32_t nativeScancode;
    uint32_t pressed;
    uint32_t reserved;
} WGUIRawKeyEvent;

typedef struct WGUIClipboardChangedEvent {
    WGUIEventHeader header;
    WGUIClipboardSelection selection;
    WGUIClipboardFlags clipboardFlags;
    uint32_t clipboardSequence;
    uint32_t reserved;
} WGUIClipboardChangedEvent;

// -- Functions ------------------------------------------------------------

#ifdef __cplusplus
extern "C" {
#endif

// Global

/**
 * The newest version of this API the host implements, as major << 16 | minor. 0 means the host
 * has no such function (it is older than every version).
 */
WGUI_IMPORT(wguiGetVersion)
uint32_t wguiGetVersion(void);

/** Whether this program may use a feature here: the host can do it and the embedder allows it. */
WGUI_IMPORT(wguiHasFeature)
WGUIBool wguiHasFeature(WGUIFeatureName feature);

/**
 * Lists the features wguiHasFeature would confirm. Writes up to `capacity` of them and sets
 * `count` to how many there are.
 */
WGUI_IMPORT(wguiGetFeatures)
WGUIStatus wguiGetFeatures(size_t capacity, WGUIFeatureName* features, size_t* count);

/**
 * Connects to the window system. NULL is WGUI_INSTANCE_DESCRIPTOR_INIT. Fails with
 * WGUIStatus_Unsupported when a required feature is missing.
 */
WGUI_IMPORT(wguiCreateInstance)
WGUIStatus wguiCreateInstance(const WGUIInstanceDescriptor* descriptor, WGUIInstance* instance);

// WGUIInstance

/**
 * Destroys the instance with everything created on it. Requests still pending complete as
 * WGUIStatus_Cancelled and are then dropped with the queue.
 */
WGUI_IMPORT(wguiInstanceDestroy)
void wguiInstanceDestroy(WGUIInstance instance);

/** What kind of host this is and what it has. */
WGUI_IMPORT(wguiInstanceGetInfo)
WGUIStatus wguiInstanceGetInfo(WGUIInstance instance, WGUIInstanceInfo* info);

/**
 * Copies queued event records into `buffer`, oldest first, as many whole records as fit, and
 * sets `written` to their total size (0 when the queue is empty). Never blocks.
 *
 * `buffer` must be 8-byte aligned and `capacity` at least WGUI_MAX_EVENT_SIZE, so one record
 * always fits. Step through the records with wguiEventFirst and wguiEventNext.
 *
 * This call and wguiInstanceWaitEvents are also where signals reach the program. A WASIX
 * runtime delivers them where a program enters the system, and a program that draws frame after
 * frame may do that nowhere else, so the host lets them in here: a handler the program
 * installed runs before the call returns, and a signal that ends the program ends it in this
 * call.
 */
WGUI_IMPORT(wguiInstancePollEvents)
WGUIStatus wguiInstancePollEvents(WGUIInstance instance, void* buffer, size_t capacity, size_t* written);

/**
 * Blocks until the queue has a record, wguiInstanceWake is called, or `timeout` nanoseconds
 * pass (0 only checks; WGUI_WAIT_FOREVER never times out). `reasons` says why it returned; 0 is
 * a timeout.
 *
 * A wake that happened before the wait is not lost: it ends the next wait. Signals reach the
 * program as this call returns, not while it sleeps in it (see wguiInstancePollEvents). So that
 * they are not kept waiting, the host ends a long wait early with WGUIWaitReasons_Interrupted:
 * unless a signal handler did something, nothing happened, and the program waits again.
 *
 * May block.
 */
WGUI_IMPORT(wguiInstanceWaitEvents)
WGUIStatus wguiInstanceWaitEvents(WGUIInstance instance, uint64_t timeout, WGUIWaitReasons* reasons);

/**
 * Ends the current wguiInstanceWaitEvents of this instance, or the next one if none is waiting.
 * For waking a program's event loop from another thread.
 */
WGUI_IMPORT(wguiInstanceWake)
WGUIStatus wguiInstanceWake(WGUIInstance instance);

/**
 * Chooses which classes of events are queued from now on. Records already queued stay.
 * WGUIEventClass_System cannot be turned off.
 */
WGUI_IMPORT(wguiInstanceSetEventMask)
WGUIStatus wguiInstanceSetEventMask(WGUIInstance instance, WGUIEventClass mask);

/**
 * The current time on the clock event timestamps use, in nanoseconds. Hosts make it the WASI
 * monotonic clock where they can.
 */
WGUI_IMPORT(wguiInstanceGetTime)
WGUIStatus wguiInstanceGetTime(WGUIInstance instance, uint64_t* time);

/**
 * Lists the displays, the primary one first. Writes up to `capacity` handles and sets `count`
 * to how many there are. Display handles stay valid until WGUIEventType_DisplaysChanged says
 * the set changed.
 */
WGUI_IMPORT(wguiInstanceGetDisplays)
WGUIStatus wguiInstanceGetDisplays(WGUIInstance instance, size_t capacity, WGUIDisplay* displays, size_t* count);

/**
 * Opens a window, or adopts the target the descriptor names. NULL asks for the host's default
 * window.
 *
 * The first record queued for the new window is a WGUIEventType_WindowResized with its real
 * size and scale factor.
 *
 * May block.
 */
WGUI_IMPORT(wguiInstanceCreateWindow)
WGUIStatus wguiInstanceCreateWindow(WGUIInstance instance, const WGUIWindowDescriptor* descriptor, WGUIWindow* window);

/** Makes a cursor from an image, for wguiWindowSetCustomCursor. */
WGUI_IMPORT(wguiInstanceCreateCursor)
WGUIStatus wguiInstanceCreateCursor(WGUIInstance instance, const WGUICursorDescriptor* descriptor, WGUICursor* cursor);

/** What the host knows about a clipboard right now, without reading it. */
WGUI_IMPORT(wguiInstanceGetClipboardInfo)
WGUIStatus wguiInstanceGetClipboardInfo(WGUIInstance instance, WGUIClipboardSelection selection, WGUIClipboardInfo* info);

/**
 * Copies the clipboard's content of one MIME type into `buffer` and sets `size` to its length
 * in bytes. Text is "text/plain", UTF-8, not NUL-terminated.
 *
 * WGUIStatus_BufferTooSmall: `size` holds what is needed, nothing was copied.
 * WGUIStatus_Pending: the host cannot answer without asking the system first (a browser); call
 * wguiInstanceRequestClipboard and read again once it completes. WGUIStatus_NotFound: nothing
 * of that type. WGUIStatus_Denied: the program may not read the clipboard.
 */
WGUI_IMPORT(wguiInstanceReadClipboard)
WGUIStatus wguiInstanceReadClipboard(WGUIInstance instance, WGUIClipboardSelection selection, const char* mimeType, size_t mimeTypeLength, void* buffer, size_t capacity, size_t* size);

/**
 * Asks the host to fetch the clipboard's content of one MIME type, so that
 * wguiInstanceReadClipboard can answer. Completes with WGUIEventType_RequestCompleted carrying
 * `tag`: Success, Denied or NotFound.
 */
WGUI_IMPORT(wguiInstanceRequestClipboard)
WGUIStatus wguiInstanceRequestClipboard(WGUIInstance instance, WGUIClipboardSelection selection, const char* mimeType, size_t mimeTypeLength, uint64_t tag);

/**
 * Replaces the clipboard's content with these items (one per MIME type; none clears it). The
 * program's own reads see the new content at once; WGUIEventType_RequestCompleted with `tag`
 * says whether the system took it.
 */
WGUI_IMPORT(wguiInstanceWriteClipboard)
WGUIStatus wguiInstanceWriteClipboard(WGUIInstance instance, WGUIClipboardSelection selection, size_t itemCount, const WGUIClipboardItem* items, uint64_t tag);

// WGUIDisplay

/** The display's geometry, scale factor and refresh rate. */
WGUI_IMPORT(wguiDisplayGetInfo)
WGUIStatus wguiDisplayGetInfo(WGUIDisplay display, WGUIDisplayInfo* info);

/**
 * The display's name for people, UTF-8, not NUL-terminated. Copies up to `capacity` bytes and
 * sets `length` to the name's full length.
 */
WGUI_IMPORT(wguiDisplayGetName)
WGUIStatus wguiDisplayGetName(WGUIDisplay display, char* buffer, size_t capacity, size_t* length);

// WGUIWindow

/**
 * Closes the window. No more records are queued for it; ones already queued can still be read.
 * A WebGPU surface created on it keeps presenting nowhere until it is released.
 */
WGUI_IMPORT(wguiWindowDestroy)
void wguiWindowDestroy(WGUIWindow window);

/**
 * The window's current size, scale factor, position and flags. Answered from what the host last
 * saw, without waiting for the window system.
 */
WGUI_IMPORT(wguiWindowGetState)
WGUIStatus wguiWindowGetState(WGUIWindow window, WGUIWindowState* state);

/**
 * The name to draw on this window with WebGPU: put it in WGPUWasixSurfaceSourceCanvas.selector.
 * UTF-8, not NUL-terminated. Copies up to `capacity` bytes and sets `length` to the full
 * length.
 *
 * For a window that adopted a named target this is that name; otherwise the host makes one up,
 * starting with "wgui:".
 */
WGUI_IMPORT(wguiWindowGetSurfaceSelector)
WGUIStatus wguiWindowGetSurfaceSelector(WGUIWindow window, char* buffer, size_t capacity, size_t* length);

/** Sets the window's title. */
WGUI_IMPORT(wguiWindowSetTitle)
WGUIStatus wguiWindowSetTitle(WGUIWindow window, const char* title, size_t titleLength);

/**
 * Asks for a new size of the content area. The size the window ends up with arrives as
 * WGUIEventType_WindowResized; WGUIStatus_Unsupported when the embedder decides the size.
 */
WGUI_IMPORT(wguiWindowSetSize)
WGUIStatus wguiWindowSetSize(WGUIWindow window, uint32_t width, uint32_t height);

/** Limits how small and how large the user can make the content area. 0 means no limit. */
WGUI_IMPORT(wguiWindowSetSizeLimits)
WGUIStatus wguiWindowSetSizeLimits(WGUIWindow window, uint32_t minWidth, uint32_t minHeight, uint32_t maxWidth, uint32_t maxHeight);

/**
 * Moves the window's content area to a position on the desktop. Needs
 * WGUIFeatureName_WindowPosition.
 */
WGUI_IMPORT(wguiWindowSetPosition)
WGUIStatus wguiWindowSetPosition(WGUIWindow window, int32_t x, int32_t y);

/**
 * Changes the flags in `mask` to their bits in `values`: show or hide, minimize, maximize,
 * restore, borders, level. What actually happened arrives as WGUIEventType_WindowFlagsChanged.
 * `unsupported` receives the bits of `mask` this host cannot change.
 */
WGUI_IMPORT(wguiWindowSetFlags)
WGUIStatus wguiWindowSetFlags(WGUIWindow window, WGUIWindowFlags mask, WGUIWindowFlags values, WGUIWindowFlags* unsupported);

/**
 * Enters fullscreen as `options` says, or leaves it when `options` is NULL. Completes with
 * WGUIEventType_RequestCompleted carrying `tag`. Where the platform insists on a user gesture
 * (a browser), the request waits for the next one unless the options forbid waiting.
 *
 * The user can leave fullscreen without the program asking; WGUIEventType_WindowFlagsChanged
 * reports every change.
 */
WGUI_IMPORT(wguiWindowSetFullscreen)
WGUIStatus wguiWindowSetFullscreen(WGUIWindow window, const WGUIFullscreenOptions* options, uint64_t tag);

/** Asks for keyboard focus and brings the window forward. Window systems may refuse. */
WGUI_IMPORT(wguiWindowFocus)
WGUIStatus wguiWindowFocus(WGUIWindow window);

/**
 * Asks for the user's attention without taking focus (a bouncing icon, a flashing task bar
 * entry).
 */
WGUI_IMPORT(wguiWindowRequestAttention)
WGUIStatus wguiWindowRequestAttention(WGUIWindow window, WGUIAttentionLevel level);

/**
 * Asks for one WGUIEventType_WindowRedrawRequested, which comes when the display is ready for
 * the window's next frame: a program that draws whenever it is told to and asks again runs at
 * the display's pace. Several requests before it is delivered make one event; none is delivered
 * while the window cannot be seen.
 */
WGUI_IMPORT(wguiWindowRequestRedraw)
WGUIStatus wguiWindowRequestRedraw(WGUIWindow window);

/** Shows one of the system's cursors over the window. */
WGUI_IMPORT(wguiWindowSetCursorShape)
WGUIStatus wguiWindowSetCursorShape(WGUIWindow window, WGUICursorShape shape);

/** Shows a cursor made with wguiInstanceCreateCursor over the window. */
WGUI_IMPORT(wguiWindowSetCustomCursor)
WGUIStatus wguiWindowSetCustomCursor(WGUIWindow window, WGUICursor cursor);

/** Shows or hides the cursor while it is over the window. */
WGUI_IMPORT(wguiWindowSetCursorVisible)
WGUIStatus wguiWindowSetCursorVisible(WGUIWindow window, WGUIBool visible);

/**
 * Keeps the cursor inside the window (Confined), or hides it and reports only movement
 * (Locked), or lets it go (None). Completes with WGUIEventType_RequestCompleted carrying `tag`;
 * a later request cancels one still pending.
 *
 * A grab is lent, not owned: the user or the system can end it, and
 * WGUIEventType_WindowCursorGrabChanged reports every change. The host never gives one kind of
 * grab in place of another.
 */
WGUI_IMPORT(wguiWindowSetCursorGrab)
WGUIStatus wguiWindowSetCursorGrab(WGUIWindow window, WGUICursorGrab grab, uint64_t tag);

/** Moves the cursor to a position in the window. Needs WGUIFeatureName_CursorWarp. */
WGUI_IMPORT(wguiWindowSetCursorPosition)
WGUIStatus wguiWindowSetCursorPosition(WGUIWindow window, double x, double y);

/**
 * Starts text entry in this window, or updates it (call again whenever the caret moves), or
 * stops it with NULL. While it is on, input methods and on-screen keyboards work, and every
 * insertion arrives as WGUIEventType_TextCommit.
 */
WGUI_IMPORT(wguiWindowSetTextInput)
WGUIStatus wguiWindowSetTextInput(WGUIWindow window, const WGUITextInputDescriptor* descriptor);

/** Throws away the text being composed, as when the program moves its caret itself. */
WGUI_IMPORT(wguiWindowResetTextInput)
WGUIStatus wguiWindowResetTextInput(WGUIWindow window);

/**
 * Says which of the embedder's own reactions to input the host should prevent while this window
 * has it (a browser scrolling the page on a wheel turn or on the space bar, its context menu).
 * A program polls for input and cannot refuse an event in time, so it states its choice ahead.
 * Hosts without such reactions accept and ignore it.
 */
WGUI_IMPORT(wguiWindowSetDefaultActions)
WGUIStatus wguiWindowSetDefaultActions(WGUIWindow window, WGUIDefaultActions prevented);

/**
 * Shows a frame the program drew itself: for programs without a GPU
 * (WGUIFeatureName_PixelPresent). The frame is copied before the call returns, so the program
 * can draw the next one into the same memory.
 *
 * The frame fills the window. One of another size than the window's is scaled to it, which a
 * program avoids by drawing at the size the last WGUIEventType_WindowResized told. `damage`
 * lists the rectangles of the frame that differ from the one presented before; none means all
 * of it. A host may show more than what is listed, never less.
 *
 * The call does not wait for the display. A program that animates asks for
 * wguiWindowRequestRedraw after each frame and draws the next one when
 * WGUIEventType_WindowRedrawRequested comes, which is once per refresh of the display; frames
 * presented faster than they can be shown replace each other. A window is drawn this way or
 * through a WebGPU surface, not both.
 */
WGUI_IMPORT(wguiWindowPresentPixels)
WGUIStatus wguiWindowPresentPixels(WGUIWindow window, const WGUIPixelFrame* frame, size_t damageCount, const WGUIRect* damage);

// WGUICursor

/** Destroys the cursor. Windows showing it go back to the default cursor. */
WGUI_IMPORT(wguiCursorDestroy)
void wguiCursorDestroy(WGUICursor cursor);

#ifdef __cplusplus
} // extern "C"
#endif

// -- Reading events -------------------------------------------------------

/**
 * The first record in a buffer that wguiInstancePollEvents filled with `written` bytes, or NULL
 * when there is none.
 *
 *     uint64_t buffer[WGUI_MAX_EVENT_SIZE / 8];
 *     size_t written = 0;
 *     wguiInstancePollEvents(instance, buffer, sizeof buffer, &written);
 *     const WGUIEventHeader* event = wguiEventFirst(buffer, written);
 *     for (; event != NULL; event = wguiEventNext(buffer, written, event)) {
 *         switch (event->type) { ... }
 *     }
 */
static inline const WGUIEventHeader* wguiEventFirst(const void* buffer, size_t written) {
    const WGUIEventHeader* event = (const WGUIEventHeader*)buffer;
    if (written < sizeof(WGUIEventHeader) || event->size < sizeof(WGUIEventHeader) || event->size > written) {
        return NULL;
    }
    return event;
}

/** The record after `event` in the same buffer, or NULL at the end. */
static inline const WGUIEventHeader* wguiEventNext(const void* buffer, size_t written, const WGUIEventHeader* event) {
    size_t next = (size_t)((const char*)event - (const char*)buffer) + event->size;
    if (next >= written) {
        return NULL;
    }
    return wguiEventFirst((const char*)buffer + next, written - next);
}

/**
 * A string of a record. It points into the record: copy it to keep it. An absent string has
 * NULL data and length 0.
 */
static inline WGUIStringView wguiEventGetString(const WGUIEventHeader* event, WGUIEventString string) {
    WGUIStringView view;
    view.data = NULL;
    view.length = 0;
    if (string.offset >= sizeof(WGUIEventHeader) && string.offset <= event->size
        && string.length <= event->size - string.offset) {
        view.data = (const char*)event + string.offset;
        view.length = string.length;
    }
    return view;
}

#endif // WASMER_GUI_H_
