// Generated by codegen/gen.py from spec/webgpu.json and spec/abi.json. Do not edit.

// Every webgpu.h function that needs no guest-side state is a tail call into the host.

#include "wgpu_imports.gen.h"

WGPUInstance wgpuCreateInstance(WGPUInstanceDescriptor const * descriptor) { return __wgpu_import_wgpuCreateInstance(descriptor); }
WGPUStatus wgpuGetInstanceLimits(WGPUInstanceLimits * limits) { return __wgpu_import_wgpuGetInstanceLimits(limits); }
WGPUBool wgpuHasInstanceFeature(WGPUInstanceFeatureName feature) { return __wgpu_import_wgpuHasInstanceFeature(feature); }
WGPUStatus wgpuAdapterGetLimits(WGPUAdapter adapter, WGPULimits * limits) { return __wgpu_import_wgpuAdapterGetLimits(adapter, limits); }
WGPUBool wgpuAdapterHasFeature(WGPUAdapter adapter, WGPUFeatureName feature) { return __wgpu_import_wgpuAdapterHasFeature(adapter, feature); }
void wgpuAdapterAddRef(WGPUAdapter adapter) { __wgpu_import_wgpuAdapterAddRef(adapter); }
void wgpuAdapterRelease(WGPUAdapter adapter) { __wgpu_import_wgpuAdapterRelease(adapter); }
void wgpuBindGroupSetLabel(WGPUBindGroup bindGroup, WGPUStringView label) { __wgpu_import_wgpuBindGroupSetLabel(bindGroup, label); }
void wgpuBindGroupAddRef(WGPUBindGroup bindGroup) { __wgpu_import_wgpuBindGroupAddRef(bindGroup); }
void wgpuBindGroupRelease(WGPUBindGroup bindGroup) { __wgpu_import_wgpuBindGroupRelease(bindGroup); }
void wgpuBindGroupLayoutSetLabel(WGPUBindGroupLayout bindGroupLayout, WGPUStringView label) { __wgpu_import_wgpuBindGroupLayoutSetLabel(bindGroupLayout, label); }
void wgpuBindGroupLayoutAddRef(WGPUBindGroupLayout bindGroupLayout) { __wgpu_import_wgpuBindGroupLayoutAddRef(bindGroupLayout); }
void wgpuBindGroupLayoutRelease(WGPUBindGroupLayout bindGroupLayout) { __wgpu_import_wgpuBindGroupLayoutRelease(bindGroupLayout); }
WGPUStatus wgpuBufferReadMappedRange(WGPUBuffer buffer, size_t offset, void * data, size_t size) { return __wgpu_import_wgpuBufferReadMappedRange(buffer, offset, data, size); }
WGPUStatus wgpuBufferWriteMappedRange(WGPUBuffer buffer, size_t offset, void const * data, size_t size) { return __wgpu_import_wgpuBufferWriteMappedRange(buffer, offset, data, size); }
void wgpuBufferSetLabel(WGPUBuffer buffer, WGPUStringView label) { __wgpu_import_wgpuBufferSetLabel(buffer, label); }
WGPUBufferUsage wgpuBufferGetUsage(WGPUBuffer buffer) { return __wgpu_import_wgpuBufferGetUsage(buffer); }
uint64_t wgpuBufferGetSize(WGPUBuffer buffer) { return __wgpu_import_wgpuBufferGetSize(buffer); }
WGPUBufferMapState wgpuBufferGetMapState(WGPUBuffer buffer) { return __wgpu_import_wgpuBufferGetMapState(buffer); }
void wgpuBufferAddRef(WGPUBuffer buffer) { __wgpu_import_wgpuBufferAddRef(buffer); }
void wgpuCommandBufferSetLabel(WGPUCommandBuffer commandBuffer, WGPUStringView label) { __wgpu_import_wgpuCommandBufferSetLabel(commandBuffer, label); }
void wgpuCommandBufferAddRef(WGPUCommandBuffer commandBuffer) { __wgpu_import_wgpuCommandBufferAddRef(commandBuffer); }
void wgpuCommandBufferRelease(WGPUCommandBuffer commandBuffer) { __wgpu_import_wgpuCommandBufferRelease(commandBuffer); }
WGPUCommandBuffer wgpuCommandEncoderFinish(WGPUCommandEncoder commandEncoder, WGPUCommandBufferDescriptor const * descriptor) { return __wgpu_import_wgpuCommandEncoderFinish(commandEncoder, descriptor); }
WGPUComputePassEncoder wgpuCommandEncoderBeginComputePass(WGPUCommandEncoder commandEncoder, WGPUComputePassDescriptor const * descriptor) { return __wgpu_import_wgpuCommandEncoderBeginComputePass(commandEncoder, descriptor); }
WGPURenderPassEncoder wgpuCommandEncoderBeginRenderPass(WGPUCommandEncoder commandEncoder, WGPURenderPassDescriptor const * descriptor) { return __wgpu_import_wgpuCommandEncoderBeginRenderPass(commandEncoder, descriptor); }
void wgpuCommandEncoderCopyBufferToBuffer(WGPUCommandEncoder commandEncoder, WGPUBuffer source, uint64_t sourceOffset, WGPUBuffer destination, uint64_t destinationOffset, uint64_t size) { __wgpu_import_wgpuCommandEncoderCopyBufferToBuffer(commandEncoder, source, sourceOffset, destination, destinationOffset, size); }
void wgpuCommandEncoderCopyBufferToTexture(WGPUCommandEncoder commandEncoder, WGPUTexelCopyBufferInfo const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize) { __wgpu_import_wgpuCommandEncoderCopyBufferToTexture(commandEncoder, source, destination, copySize); }
void wgpuCommandEncoderCopyTextureToBuffer(WGPUCommandEncoder commandEncoder, WGPUTexelCopyTextureInfo const * source, WGPUTexelCopyBufferInfo const * destination, WGPUExtent3D const * copySize) { __wgpu_import_wgpuCommandEncoderCopyTextureToBuffer(commandEncoder, source, destination, copySize); }
void wgpuCommandEncoderCopyTextureToTexture(WGPUCommandEncoder commandEncoder, WGPUTexelCopyTextureInfo const * source, WGPUTexelCopyTextureInfo const * destination, WGPUExtent3D const * copySize) { __wgpu_import_wgpuCommandEncoderCopyTextureToTexture(commandEncoder, source, destination, copySize); }
void wgpuCommandEncoderClearBuffer(WGPUCommandEncoder commandEncoder, WGPUBuffer buffer, uint64_t offset, uint64_t size) { __wgpu_import_wgpuCommandEncoderClearBuffer(commandEncoder, buffer, offset, size); }
void wgpuCommandEncoderInsertDebugMarker(WGPUCommandEncoder commandEncoder, WGPUStringView markerLabel) { __wgpu_import_wgpuCommandEncoderInsertDebugMarker(commandEncoder, markerLabel); }
void wgpuCommandEncoderPopDebugGroup(WGPUCommandEncoder commandEncoder) { __wgpu_import_wgpuCommandEncoderPopDebugGroup(commandEncoder); }
void wgpuCommandEncoderPushDebugGroup(WGPUCommandEncoder commandEncoder, WGPUStringView groupLabel) { __wgpu_import_wgpuCommandEncoderPushDebugGroup(commandEncoder, groupLabel); }
void wgpuCommandEncoderResolveQuerySet(WGPUCommandEncoder commandEncoder, WGPUQuerySet querySet, uint32_t firstQuery, uint32_t queryCount, WGPUBuffer destination, uint64_t destinationOffset) { __wgpu_import_wgpuCommandEncoderResolveQuerySet(commandEncoder, querySet, firstQuery, queryCount, destination, destinationOffset); }
void wgpuCommandEncoderWriteTimestamp(WGPUCommandEncoder commandEncoder, WGPUQuerySet querySet, uint32_t queryIndex) { __wgpu_import_wgpuCommandEncoderWriteTimestamp(commandEncoder, querySet, queryIndex); }
void wgpuCommandEncoderSetLabel(WGPUCommandEncoder commandEncoder, WGPUStringView label) { __wgpu_import_wgpuCommandEncoderSetLabel(commandEncoder, label); }
void wgpuCommandEncoderAddRef(WGPUCommandEncoder commandEncoder) { __wgpu_import_wgpuCommandEncoderAddRef(commandEncoder); }
void wgpuCommandEncoderRelease(WGPUCommandEncoder commandEncoder) { __wgpu_import_wgpuCommandEncoderRelease(commandEncoder); }
void wgpuComputePassEncoderInsertDebugMarker(WGPUComputePassEncoder computePassEncoder, WGPUStringView markerLabel) { __wgpu_import_wgpuComputePassEncoderInsertDebugMarker(computePassEncoder, markerLabel); }
void wgpuComputePassEncoderPopDebugGroup(WGPUComputePassEncoder computePassEncoder) { __wgpu_import_wgpuComputePassEncoderPopDebugGroup(computePassEncoder); }
void wgpuComputePassEncoderPushDebugGroup(WGPUComputePassEncoder computePassEncoder, WGPUStringView groupLabel) { __wgpu_import_wgpuComputePassEncoderPushDebugGroup(computePassEncoder, groupLabel); }
void wgpuComputePassEncoderSetPipeline(WGPUComputePassEncoder computePassEncoder, WGPUComputePipeline pipeline) { __wgpu_import_wgpuComputePassEncoderSetPipeline(computePassEncoder, pipeline); }
void wgpuComputePassEncoderSetBindGroup(WGPUComputePassEncoder computePassEncoder, uint32_t groupIndex, WGPUBindGroup group, size_t dynamicOffsetCount, uint32_t const * dynamicOffsets) { __wgpu_import_wgpuComputePassEncoderSetBindGroup(computePassEncoder, groupIndex, group, dynamicOffsetCount, dynamicOffsets); }
void wgpuComputePassEncoderSetImmediates(WGPUComputePassEncoder computePassEncoder, uint32_t offset, void const * data, size_t size) { __wgpu_import_wgpuComputePassEncoderSetImmediates(computePassEncoder, offset, data, size); }
void wgpuComputePassEncoderDispatchWorkgroups(WGPUComputePassEncoder computePassEncoder, uint32_t workgroupCountX, uint32_t workgroupCountY, uint32_t workgroupCountZ) { __wgpu_import_wgpuComputePassEncoderDispatchWorkgroups(computePassEncoder, workgroupCountX, workgroupCountY, workgroupCountZ); }
void wgpuComputePassEncoderDispatchWorkgroupsIndirect(WGPUComputePassEncoder computePassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wgpu_import_wgpuComputePassEncoderDispatchWorkgroupsIndirect(computePassEncoder, indirectBuffer, indirectOffset); }
void wgpuComputePassEncoderEnd(WGPUComputePassEncoder computePassEncoder) { __wgpu_import_wgpuComputePassEncoderEnd(computePassEncoder); }
void wgpuComputePassEncoderSetLabel(WGPUComputePassEncoder computePassEncoder, WGPUStringView label) { __wgpu_import_wgpuComputePassEncoderSetLabel(computePassEncoder, label); }
void wgpuComputePassEncoderAddRef(WGPUComputePassEncoder computePassEncoder) { __wgpu_import_wgpuComputePassEncoderAddRef(computePassEncoder); }
void wgpuComputePassEncoderRelease(WGPUComputePassEncoder computePassEncoder) { __wgpu_import_wgpuComputePassEncoderRelease(computePassEncoder); }
WGPUBindGroupLayout wgpuComputePipelineGetBindGroupLayout(WGPUComputePipeline computePipeline, uint32_t groupIndex) { return __wgpu_import_wgpuComputePipelineGetBindGroupLayout(computePipeline, groupIndex); }
void wgpuComputePipelineSetLabel(WGPUComputePipeline computePipeline, WGPUStringView label) { __wgpu_import_wgpuComputePipelineSetLabel(computePipeline, label); }
void wgpuComputePipelineAddRef(WGPUComputePipeline computePipeline) { __wgpu_import_wgpuComputePipelineAddRef(computePipeline); }
void wgpuComputePipelineRelease(WGPUComputePipeline computePipeline) { __wgpu_import_wgpuComputePipelineRelease(computePipeline); }
WGPUBindGroup wgpuDeviceCreateBindGroup(WGPUDevice device, WGPUBindGroupDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateBindGroup(device, descriptor); }
WGPUBindGroupLayout wgpuDeviceCreateBindGroupLayout(WGPUDevice device, WGPUBindGroupLayoutDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateBindGroupLayout(device, descriptor); }
WGPUBuffer wgpuDeviceCreateBuffer(WGPUDevice device, WGPUBufferDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateBuffer(device, descriptor); }
WGPUCommandEncoder wgpuDeviceCreateCommandEncoder(WGPUDevice device, WGPUCommandEncoderDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateCommandEncoder(device, descriptor); }
WGPUComputePipeline wgpuDeviceCreateComputePipeline(WGPUDevice device, WGPUComputePipelineDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateComputePipeline(device, descriptor); }
WGPUPipelineLayout wgpuDeviceCreatePipelineLayout(WGPUDevice device, WGPUPipelineLayoutDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreatePipelineLayout(device, descriptor); }
WGPUQuerySet wgpuDeviceCreateQuerySet(WGPUDevice device, WGPUQuerySetDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateQuerySet(device, descriptor); }
WGPURenderBundleEncoder wgpuDeviceCreateRenderBundleEncoder(WGPUDevice device, WGPURenderBundleEncoderDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateRenderBundleEncoder(device, descriptor); }
WGPURenderPipeline wgpuDeviceCreateRenderPipeline(WGPUDevice device, WGPURenderPipelineDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateRenderPipeline(device, descriptor); }
WGPUSampler wgpuDeviceCreateSampler(WGPUDevice device, WGPUSamplerDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateSampler(device, descriptor); }
WGPUShaderModule wgpuDeviceCreateShaderModule(WGPUDevice device, WGPUShaderModuleDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateShaderModule(device, descriptor); }
WGPUTexture wgpuDeviceCreateTexture(WGPUDevice device, WGPUTextureDescriptor const * descriptor) { return __wgpu_import_wgpuDeviceCreateTexture(device, descriptor); }
void wgpuDeviceDestroy(WGPUDevice device) { __wgpu_import_wgpuDeviceDestroy(device); }
WGPUStatus wgpuDeviceGetLimits(WGPUDevice device, WGPULimits * limits) { return __wgpu_import_wgpuDeviceGetLimits(device, limits); }
WGPUBool wgpuDeviceHasFeature(WGPUDevice device, WGPUFeatureName feature) { return __wgpu_import_wgpuDeviceHasFeature(device, feature); }
WGPUQueue wgpuDeviceGetQueue(WGPUDevice device) { return __wgpu_import_wgpuDeviceGetQueue(device); }
void wgpuDevicePushErrorScope(WGPUDevice device, WGPUErrorFilter filter) { __wgpu_import_wgpuDevicePushErrorScope(device, filter); }
void wgpuDeviceSetLabel(WGPUDevice device, WGPUStringView label) { __wgpu_import_wgpuDeviceSetLabel(device, label); }
void wgpuDeviceAddRef(WGPUDevice device) { __wgpu_import_wgpuDeviceAddRef(device); }
void wgpuExternalTextureSetLabel(WGPUExternalTexture externalTexture, WGPUStringView label) { __wgpu_import_wgpuExternalTextureSetLabel(externalTexture, label); }
void wgpuExternalTextureAddRef(WGPUExternalTexture externalTexture) { __wgpu_import_wgpuExternalTextureAddRef(externalTexture); }
void wgpuExternalTextureRelease(WGPUExternalTexture externalTexture) { __wgpu_import_wgpuExternalTextureRelease(externalTexture); }
WGPUSurface wgpuInstanceCreateSurface(WGPUInstance instance, WGPUSurfaceDescriptor const * descriptor) { return __wgpu_import_wgpuInstanceCreateSurface(instance, descriptor); }
WGPUBool wgpuInstanceHasWGSLLanguageFeature(WGPUInstance instance, WGPUWGSLLanguageFeatureName feature) { return __wgpu_import_wgpuInstanceHasWGSLLanguageFeature(instance, feature); }
void wgpuInstanceAddRef(WGPUInstance instance) { __wgpu_import_wgpuInstanceAddRef(instance); }
void wgpuPipelineLayoutSetLabel(WGPUPipelineLayout pipelineLayout, WGPUStringView label) { __wgpu_import_wgpuPipelineLayoutSetLabel(pipelineLayout, label); }
void wgpuPipelineLayoutAddRef(WGPUPipelineLayout pipelineLayout) { __wgpu_import_wgpuPipelineLayoutAddRef(pipelineLayout); }
void wgpuPipelineLayoutRelease(WGPUPipelineLayout pipelineLayout) { __wgpu_import_wgpuPipelineLayoutRelease(pipelineLayout); }
void wgpuQuerySetSetLabel(WGPUQuerySet querySet, WGPUStringView label) { __wgpu_import_wgpuQuerySetSetLabel(querySet, label); }
WGPUQueryType wgpuQuerySetGetType(WGPUQuerySet querySet) { return __wgpu_import_wgpuQuerySetGetType(querySet); }
uint32_t wgpuQuerySetGetCount(WGPUQuerySet querySet) { return __wgpu_import_wgpuQuerySetGetCount(querySet); }
void wgpuQuerySetDestroy(WGPUQuerySet querySet) { __wgpu_import_wgpuQuerySetDestroy(querySet); }
void wgpuQuerySetAddRef(WGPUQuerySet querySet) { __wgpu_import_wgpuQuerySetAddRef(querySet); }
void wgpuQuerySetRelease(WGPUQuerySet querySet) { __wgpu_import_wgpuQuerySetRelease(querySet); }
void wgpuQueueSubmit(WGPUQueue queue, size_t commandCount, WGPUCommandBuffer const * commands) { __wgpu_import_wgpuQueueSubmit(queue, commandCount, commands); }
void wgpuQueueWriteBuffer(WGPUQueue queue, WGPUBuffer buffer, uint64_t bufferOffset, void const * data, size_t size) { __wgpu_import_wgpuQueueWriteBuffer(queue, buffer, bufferOffset, data, size); }
void wgpuQueueWriteTexture(WGPUQueue queue, WGPUTexelCopyTextureInfo const * destination, void const * data, size_t dataSize, WGPUTexelCopyBufferLayout const * dataLayout, WGPUExtent3D const * writeSize) { __wgpu_import_wgpuQueueWriteTexture(queue, destination, data, dataSize, dataLayout, writeSize); }
void wgpuQueueSetLabel(WGPUQueue queue, WGPUStringView label) { __wgpu_import_wgpuQueueSetLabel(queue, label); }
void wgpuQueueAddRef(WGPUQueue queue) { __wgpu_import_wgpuQueueAddRef(queue); }
void wgpuQueueRelease(WGPUQueue queue) { __wgpu_import_wgpuQueueRelease(queue); }
void wgpuRenderBundleSetLabel(WGPURenderBundle renderBundle, WGPUStringView label) { __wgpu_import_wgpuRenderBundleSetLabel(renderBundle, label); }
void wgpuRenderBundleAddRef(WGPURenderBundle renderBundle) { __wgpu_import_wgpuRenderBundleAddRef(renderBundle); }
void wgpuRenderBundleRelease(WGPURenderBundle renderBundle) { __wgpu_import_wgpuRenderBundleRelease(renderBundle); }
void wgpuRenderBundleEncoderSetPipeline(WGPURenderBundleEncoder renderBundleEncoder, WGPURenderPipeline pipeline) { __wgpu_import_wgpuRenderBundleEncoderSetPipeline(renderBundleEncoder, pipeline); }
void wgpuRenderBundleEncoderSetBindGroup(WGPURenderBundleEncoder renderBundleEncoder, uint32_t groupIndex, WGPUBindGroup group, size_t dynamicOffsetCount, uint32_t const * dynamicOffsets) { __wgpu_import_wgpuRenderBundleEncoderSetBindGroup(renderBundleEncoder, groupIndex, group, dynamicOffsetCount, dynamicOffsets); }
void wgpuRenderBundleEncoderSetImmediates(WGPURenderBundleEncoder renderBundleEncoder, uint32_t offset, void const * data, size_t size) { __wgpu_import_wgpuRenderBundleEncoderSetImmediates(renderBundleEncoder, offset, data, size); }
void wgpuRenderBundleEncoderDraw(WGPURenderBundleEncoder renderBundleEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance) { __wgpu_import_wgpuRenderBundleEncoderDraw(renderBundleEncoder, vertexCount, instanceCount, firstVertex, firstInstance); }
void wgpuRenderBundleEncoderDrawIndexed(WGPURenderBundleEncoder renderBundleEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance) { __wgpu_import_wgpuRenderBundleEncoderDrawIndexed(renderBundleEncoder, indexCount, instanceCount, firstIndex, baseVertex, firstInstance); }
void wgpuRenderBundleEncoderDrawIndirect(WGPURenderBundleEncoder renderBundleEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wgpu_import_wgpuRenderBundleEncoderDrawIndirect(renderBundleEncoder, indirectBuffer, indirectOffset); }
void wgpuRenderBundleEncoderDrawIndexedIndirect(WGPURenderBundleEncoder renderBundleEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wgpu_import_wgpuRenderBundleEncoderDrawIndexedIndirect(renderBundleEncoder, indirectBuffer, indirectOffset); }
void wgpuRenderBundleEncoderInsertDebugMarker(WGPURenderBundleEncoder renderBundleEncoder, WGPUStringView markerLabel) { __wgpu_import_wgpuRenderBundleEncoderInsertDebugMarker(renderBundleEncoder, markerLabel); }
void wgpuRenderBundleEncoderPopDebugGroup(WGPURenderBundleEncoder renderBundleEncoder) { __wgpu_import_wgpuRenderBundleEncoderPopDebugGroup(renderBundleEncoder); }
void wgpuRenderBundleEncoderPushDebugGroup(WGPURenderBundleEncoder renderBundleEncoder, WGPUStringView groupLabel) { __wgpu_import_wgpuRenderBundleEncoderPushDebugGroup(renderBundleEncoder, groupLabel); }
void wgpuRenderBundleEncoderSetVertexBuffer(WGPURenderBundleEncoder renderBundleEncoder, uint32_t slot, WGPUBuffer buffer, uint64_t offset, uint64_t size) { __wgpu_import_wgpuRenderBundleEncoderSetVertexBuffer(renderBundleEncoder, slot, buffer, offset, size); }
void wgpuRenderBundleEncoderSetIndexBuffer(WGPURenderBundleEncoder renderBundleEncoder, WGPUBuffer buffer, WGPUIndexFormat format, uint64_t offset, uint64_t size) { __wgpu_import_wgpuRenderBundleEncoderSetIndexBuffer(renderBundleEncoder, buffer, format, offset, size); }
WGPURenderBundle wgpuRenderBundleEncoderFinish(WGPURenderBundleEncoder renderBundleEncoder, WGPURenderBundleDescriptor const * descriptor) { return __wgpu_import_wgpuRenderBundleEncoderFinish(renderBundleEncoder, descriptor); }
void wgpuRenderBundleEncoderSetLabel(WGPURenderBundleEncoder renderBundleEncoder, WGPUStringView label) { __wgpu_import_wgpuRenderBundleEncoderSetLabel(renderBundleEncoder, label); }
void wgpuRenderBundleEncoderAddRef(WGPURenderBundleEncoder renderBundleEncoder) { __wgpu_import_wgpuRenderBundleEncoderAddRef(renderBundleEncoder); }
void wgpuRenderBundleEncoderRelease(WGPURenderBundleEncoder renderBundleEncoder) { __wgpu_import_wgpuRenderBundleEncoderRelease(renderBundleEncoder); }
void wgpuRenderPassEncoderSetPipeline(WGPURenderPassEncoder renderPassEncoder, WGPURenderPipeline pipeline) { __wgpu_import_wgpuRenderPassEncoderSetPipeline(renderPassEncoder, pipeline); }
void wgpuRenderPassEncoderSetBindGroup(WGPURenderPassEncoder renderPassEncoder, uint32_t groupIndex, WGPUBindGroup group, size_t dynamicOffsetCount, uint32_t const * dynamicOffsets) { __wgpu_import_wgpuRenderPassEncoderSetBindGroup(renderPassEncoder, groupIndex, group, dynamicOffsetCount, dynamicOffsets); }
void wgpuRenderPassEncoderSetImmediates(WGPURenderPassEncoder renderPassEncoder, uint32_t offset, void const * data, size_t size) { __wgpu_import_wgpuRenderPassEncoderSetImmediates(renderPassEncoder, offset, data, size); }
void wgpuRenderPassEncoderDraw(WGPURenderPassEncoder renderPassEncoder, uint32_t vertexCount, uint32_t instanceCount, uint32_t firstVertex, uint32_t firstInstance) { __wgpu_import_wgpuRenderPassEncoderDraw(renderPassEncoder, vertexCount, instanceCount, firstVertex, firstInstance); }
void wgpuRenderPassEncoderDrawIndexed(WGPURenderPassEncoder renderPassEncoder, uint32_t indexCount, uint32_t instanceCount, uint32_t firstIndex, int32_t baseVertex, uint32_t firstInstance) { __wgpu_import_wgpuRenderPassEncoderDrawIndexed(renderPassEncoder, indexCount, instanceCount, firstIndex, baseVertex, firstInstance); }
void wgpuRenderPassEncoderDrawIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wgpu_import_wgpuRenderPassEncoderDrawIndirect(renderPassEncoder, indirectBuffer, indirectOffset); }
void wgpuRenderPassEncoderDrawIndexedIndirect(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer indirectBuffer, uint64_t indirectOffset) { __wgpu_import_wgpuRenderPassEncoderDrawIndexedIndirect(renderPassEncoder, indirectBuffer, indirectOffset); }
void wgpuRenderPassEncoderExecuteBundles(WGPURenderPassEncoder renderPassEncoder, size_t bundleCount, WGPURenderBundle const * bundles) { __wgpu_import_wgpuRenderPassEncoderExecuteBundles(renderPassEncoder, bundleCount, bundles); }
void wgpuRenderPassEncoderInsertDebugMarker(WGPURenderPassEncoder renderPassEncoder, WGPUStringView markerLabel) { __wgpu_import_wgpuRenderPassEncoderInsertDebugMarker(renderPassEncoder, markerLabel); }
void wgpuRenderPassEncoderPopDebugGroup(WGPURenderPassEncoder renderPassEncoder) { __wgpu_import_wgpuRenderPassEncoderPopDebugGroup(renderPassEncoder); }
void wgpuRenderPassEncoderPushDebugGroup(WGPURenderPassEncoder renderPassEncoder, WGPUStringView groupLabel) { __wgpu_import_wgpuRenderPassEncoderPushDebugGroup(renderPassEncoder, groupLabel); }
void wgpuRenderPassEncoderSetStencilReference(WGPURenderPassEncoder renderPassEncoder, uint32_t reference) { __wgpu_import_wgpuRenderPassEncoderSetStencilReference(renderPassEncoder, reference); }
void wgpuRenderPassEncoderSetBlendConstant(WGPURenderPassEncoder renderPassEncoder, WGPUColor const * color) { __wgpu_import_wgpuRenderPassEncoderSetBlendConstant(renderPassEncoder, color); }
void wgpuRenderPassEncoderSetViewport(WGPURenderPassEncoder renderPassEncoder, float x, float y, float width, float height, float minDepth, float maxDepth) { __wgpu_import_wgpuRenderPassEncoderSetViewport(renderPassEncoder, x, y, width, height, minDepth, maxDepth); }
void wgpuRenderPassEncoderSetScissorRect(WGPURenderPassEncoder renderPassEncoder, uint32_t x, uint32_t y, uint32_t width, uint32_t height) { __wgpu_import_wgpuRenderPassEncoderSetScissorRect(renderPassEncoder, x, y, width, height); }
void wgpuRenderPassEncoderSetVertexBuffer(WGPURenderPassEncoder renderPassEncoder, uint32_t slot, WGPUBuffer buffer, uint64_t offset, uint64_t size) { __wgpu_import_wgpuRenderPassEncoderSetVertexBuffer(renderPassEncoder, slot, buffer, offset, size); }
void wgpuRenderPassEncoderSetIndexBuffer(WGPURenderPassEncoder renderPassEncoder, WGPUBuffer buffer, WGPUIndexFormat format, uint64_t offset, uint64_t size) { __wgpu_import_wgpuRenderPassEncoderSetIndexBuffer(renderPassEncoder, buffer, format, offset, size); }
void wgpuRenderPassEncoderBeginOcclusionQuery(WGPURenderPassEncoder renderPassEncoder, uint32_t queryIndex) { __wgpu_import_wgpuRenderPassEncoderBeginOcclusionQuery(renderPassEncoder, queryIndex); }
void wgpuRenderPassEncoderEndOcclusionQuery(WGPURenderPassEncoder renderPassEncoder) { __wgpu_import_wgpuRenderPassEncoderEndOcclusionQuery(renderPassEncoder); }
void wgpuRenderPassEncoderEnd(WGPURenderPassEncoder renderPassEncoder) { __wgpu_import_wgpuRenderPassEncoderEnd(renderPassEncoder); }
void wgpuRenderPassEncoderSetLabel(WGPURenderPassEncoder renderPassEncoder, WGPUStringView label) { __wgpu_import_wgpuRenderPassEncoderSetLabel(renderPassEncoder, label); }
void wgpuRenderPassEncoderAddRef(WGPURenderPassEncoder renderPassEncoder) { __wgpu_import_wgpuRenderPassEncoderAddRef(renderPassEncoder); }
void wgpuRenderPassEncoderRelease(WGPURenderPassEncoder renderPassEncoder) { __wgpu_import_wgpuRenderPassEncoderRelease(renderPassEncoder); }
WGPUBindGroupLayout wgpuRenderPipelineGetBindGroupLayout(WGPURenderPipeline renderPipeline, uint32_t groupIndex) { return __wgpu_import_wgpuRenderPipelineGetBindGroupLayout(renderPipeline, groupIndex); }
void wgpuRenderPipelineSetLabel(WGPURenderPipeline renderPipeline, WGPUStringView label) { __wgpu_import_wgpuRenderPipelineSetLabel(renderPipeline, label); }
void wgpuRenderPipelineAddRef(WGPURenderPipeline renderPipeline) { __wgpu_import_wgpuRenderPipelineAddRef(renderPipeline); }
void wgpuRenderPipelineRelease(WGPURenderPipeline renderPipeline) { __wgpu_import_wgpuRenderPipelineRelease(renderPipeline); }
void wgpuSamplerSetLabel(WGPUSampler sampler, WGPUStringView label) { __wgpu_import_wgpuSamplerSetLabel(sampler, label); }
void wgpuSamplerAddRef(WGPUSampler sampler) { __wgpu_import_wgpuSamplerAddRef(sampler); }
void wgpuSamplerRelease(WGPUSampler sampler) { __wgpu_import_wgpuSamplerRelease(sampler); }
void wgpuShaderModuleSetLabel(WGPUShaderModule shaderModule, WGPUStringView label) { __wgpu_import_wgpuShaderModuleSetLabel(shaderModule, label); }
void wgpuShaderModuleAddRef(WGPUShaderModule shaderModule) { __wgpu_import_wgpuShaderModuleAddRef(shaderModule); }
void wgpuShaderModuleRelease(WGPUShaderModule shaderModule) { __wgpu_import_wgpuShaderModuleRelease(shaderModule); }
void wgpuSurfaceConfigure(WGPUSurface surface, WGPUSurfaceConfiguration const * config) { __wgpu_import_wgpuSurfaceConfigure(surface, config); }
void wgpuSurfaceGetCurrentTexture(WGPUSurface surface, WGPUSurfaceTexture * surfaceTexture) { __wgpu_import_wgpuSurfaceGetCurrentTexture(surface, surfaceTexture); }
WGPUStatus wgpuSurfacePresent(WGPUSurface surface) { return __wgpu_import_wgpuSurfacePresent(surface); }
void wgpuSurfaceUnconfigure(WGPUSurface surface) { __wgpu_import_wgpuSurfaceUnconfigure(surface); }
void wgpuSurfaceSetLabel(WGPUSurface surface, WGPUStringView label) { __wgpu_import_wgpuSurfaceSetLabel(surface, label); }
void wgpuSurfaceAddRef(WGPUSurface surface) { __wgpu_import_wgpuSurfaceAddRef(surface); }
void wgpuSurfaceRelease(WGPUSurface surface) { __wgpu_import_wgpuSurfaceRelease(surface); }
WGPUTextureView wgpuTextureCreateView(WGPUTexture texture, WGPUTextureViewDescriptor const * descriptor) { return __wgpu_import_wgpuTextureCreateView(texture, descriptor); }
void wgpuTextureSetLabel(WGPUTexture texture, WGPUStringView label) { __wgpu_import_wgpuTextureSetLabel(texture, label); }
uint32_t wgpuTextureGetWidth(WGPUTexture texture) { return __wgpu_import_wgpuTextureGetWidth(texture); }
uint32_t wgpuTextureGetHeight(WGPUTexture texture) { return __wgpu_import_wgpuTextureGetHeight(texture); }
uint32_t wgpuTextureGetDepthOrArrayLayers(WGPUTexture texture) { return __wgpu_import_wgpuTextureGetDepthOrArrayLayers(texture); }
uint32_t wgpuTextureGetMipLevelCount(WGPUTexture texture) { return __wgpu_import_wgpuTextureGetMipLevelCount(texture); }
uint32_t wgpuTextureGetSampleCount(WGPUTexture texture) { return __wgpu_import_wgpuTextureGetSampleCount(texture); }
WGPUTextureDimension wgpuTextureGetDimension(WGPUTexture texture) { return __wgpu_import_wgpuTextureGetDimension(texture); }
WGPUTextureViewDimension wgpuTextureGetTextureBindingViewDimension(WGPUTexture texture) { return __wgpu_import_wgpuTextureGetTextureBindingViewDimension(texture); }
WGPUTextureFormat wgpuTextureGetFormat(WGPUTexture texture) { return __wgpu_import_wgpuTextureGetFormat(texture); }
WGPUTextureUsage wgpuTextureGetUsage(WGPUTexture texture) { return __wgpu_import_wgpuTextureGetUsage(texture); }
void wgpuTextureDestroy(WGPUTexture texture) { __wgpu_import_wgpuTextureDestroy(texture); }
void wgpuTextureAddRef(WGPUTexture texture) { __wgpu_import_wgpuTextureAddRef(texture); }
void wgpuTextureRelease(WGPUTexture texture) { __wgpu_import_wgpuTextureRelease(texture); }
void wgpuTextureViewSetLabel(WGPUTextureView textureView, WGPUStringView label) { __wgpu_import_wgpuTextureViewSetLabel(textureView, label); }
void wgpuTextureViewAddRef(WGPUTextureView textureView) { __wgpu_import_wgpuTextureViewAddRef(textureView); }
void wgpuTextureViewRelease(WGPUTextureView textureView) { __wgpu_import_wgpuTextureViewRelease(textureView); }
WGPUStatus wgpuWasixSurfaceGetSize(WGPUSurface surface, uint32_t * width, uint32_t * height) { return __wgpu_import_wgpuWasixSurfaceGetSize(surface, width, height); }
